version: "3"

services:
  mussa_frontend:
    build: .
    ports:
     - "5000:5000"
    depends_on:
     - db
     - redis
    networks:
     - db_network
     - redis_network
    environment:
      MUSSA_DB_USER:
      MUSSA_DB_PASS:
      MYSQL_ROOT_PASSWORD:
      MUSSA_DB_NAME: "mussa"
      MUSSA_DB_HOST: "db"
    volumes:
      - ./init-scripts:/init-scripts
  
  db:
    image: mariadb
    networks:
     - db_network
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
     - ./mysql-data:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p", "$${MYSQL_ROOT_PASSWORD}"]
     timeout: 20s
     retries: 10
  redis:
    image: redis
    networks:
     - redis_network


networks:
  db_network:
  redis_network:

