ENTER = "\n"
MAX_CUATRIMESTRES_TOTALES = 2#10
NOMBRE_PROBLEMA = "Jenny_Calculo_plan_carrera"
MAX_CANTIDAD_MATERIAS_POR_CUATRIMESTRE = 2#3

INFINITO = 10000

LUNES = "LUNES"
MARTES = "MARTES"
MIERCOLES = "MIERCOLES"
JUEVES = "JUEVES"
VIERNES = "VIERNES"
SABADO = "SABADO"
DIAS = [LUNES]#, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO]


CANT_DIAS = 6
HORA_ORIGEN = 7
FRANJA_MIN = 1 #Corresponde al horario de 07:00 a 07:30 --> 1
FRANJA_MAX = 12 #Corresponde al horario de 23:00 a 23:30 --> 33

#Tipos de materias
OBLIGATORIA = 0
ELECTIVA = 1

TIPOS_MATERIAS = {
	OBLIGATORIA: "Obligatoria",
	ELECTIVA: "Electiva"
}