ENTER = "\n"
MAX_CUATRIMESTRES_TOTALES = 10
NOMBRE_PROBLEMA = "Jenny_Calculo_plan_carrera"
MAX_CANTIDAD_MATERIAS_POR_CUATRIMESTRE = 3

LUNES = "LUNES"
MARTES = "MARTES"
MIERCOLES = "MIERCOLES"
JUEVES = "JUEVES"
VIERNES = "VIERNES"
SABADO = "SABADO"
DIAS = [LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO]


CANT_DIAS = 6
HORA_ORIGEN = 7
FRANJA_MIN = 1 #Corresponde al horario de 07:00 a 07:30
FRANJA_MAX = 33 #33 #Corresponde al horario de 23:00 a 23:30

