from pulp import *
from time import time


#Yij: La materia i se realiza en el cuatrimestre j

Y_H_1 = LpVariable(name='Y_H_1', cat='Binary')
Y_H_2 = LpVariable(name='Y_H_2', cat='Binary')
Y_D_1 = LpVariable(name='Y_D_1', cat='Binary')
Y_D_2 = LpVariable(name='Y_D_2', cat='Binary')
Y_I_1 = LpVariable(name='Y_I_1', cat='Binary')
Y_I_2 = LpVariable(name='Y_I_2', cat='Binary')
Y_C_1 = LpVariable(name='Y_C_1', cat='Binary')
Y_C_2 = LpVariable(name='Y_C_2', cat='Binary')
Y_E_1 = LpVariable(name='Y_E_1', cat='Binary')
Y_E_2 = LpVariable(name='Y_E_2', cat='Binary')
Y_J_1 = LpVariable(name='Y_J_1', cat='Binary')
Y_J_2 = LpVariable(name='Y_J_2', cat='Binary')
Y_A_1 = LpVariable(name='Y_A_1', cat='Binary')
Y_A_2 = LpVariable(name='Y_A_2', cat='Binary')
Y_G_1 = LpVariable(name='Y_G_1', cat='Binary')
Y_G_2 = LpVariable(name='Y_G_2', cat='Binary')
Y_B_1 = LpVariable(name='Y_B_1', cat='Binary')
Y_B_2 = LpVariable(name='Y_B_2', cat='Binary')
Y_F_1 = LpVariable(name='Y_F_1', cat='Binary')
Y_F_2 = LpVariable(name='Y_F_2', cat='Binary')


#Ci: Numero de cuatrimestre en que se hace la materia i. Ejemplo, si Ci=3 es que la materia i se hace el cuatrimestre numero 3

CH = LpVariable(name='CH', cat='Integer')
CD = LpVariable(name='CD', cat='Integer')
CI = LpVariable(name='CI', cat='Integer')
CC = LpVariable(name='CC', cat='Integer')
CE = LpVariable(name='CE', cat='Integer')
CJ = LpVariable(name='CJ', cat='Integer')
CA = LpVariable(name='CA', cat='Integer')
CG = LpVariable(name='CG', cat='Integer')
CB = LpVariable(name='CB', cat='Integer')
CF = LpVariable(name='CF', cat='Integer')


#TOTAL_CUATRIMESTRES: Total de cuatrimestres a cursar. Utilizada para escribir el maximo entre Ci MAX(CA, CB..)

TOTAL_CUATRIMESTRES = LpVariable(name='TOTAL_CUATRIMESTRES', cat='Integer')

#CREDi: Cantidad de creditos al final del cuatrimestre i

CRED0 = LpVariable(name='CRED0', cat='Integer')
CRED1 = LpVariable(name='CRED1', cat='Integer')


#H_{materia i}_{nombre del curso j}_{cuatrimestre k}: La materia i se cursa en el curso j en el cuatrimestre k

H_H_Curso1H_1 = LpVariable(name='H_H_Curso1H_1', cat='Binary')
H_D_Curso1D_1 = LpVariable(name='H_D_Curso1D_1', cat='Binary')
H_I_Curso1I_1 = LpVariable(name='H_I_Curso1I_1', cat='Binary')
H_C_Curso1C_1 = LpVariable(name='H_C_Curso1C_1', cat='Binary')
H_E_Curso1E_1 = LpVariable(name='H_E_Curso1E_1', cat='Binary')
H_J_Curso1J_1 = LpVariable(name='H_J_Curso1J_1', cat='Binary')
H_A_Curso1A_1 = LpVariable(name='H_A_Curso1A_1', cat='Binary')
H_G_Curso1G_1 = LpVariable(name='H_G_Curso1G_1', cat='Binary')
H_B_Curso1B_1 = LpVariable(name='H_B_Curso1B_1', cat='Binary')
H_F_Curso1F_1 = LpVariable(name='H_F_Curso1F_1', cat='Binary')
H_H_Curso1H_2 = LpVariable(name='H_H_Curso1H_2', cat='Binary')
H_D_Curso1D_2 = LpVariable(name='H_D_Curso1D_2', cat='Binary')
H_I_Curso1I_2 = LpVariable(name='H_I_Curso1I_2', cat='Binary')
H_C_Curso1C_2 = LpVariable(name='H_C_Curso1C_2', cat='Binary')
H_E_Curso1E_2 = LpVariable(name='H_E_Curso1E_2', cat='Binary')
H_J_Curso1J_2 = LpVariable(name='H_J_Curso1J_2', cat='Binary')
H_A_Curso1A_2 = LpVariable(name='H_A_Curso1A_2', cat='Binary')
H_G_Curso1G_2 = LpVariable(name='H_G_Curso1G_2', cat='Binary')
H_B_Curso1B_2 = LpVariable(name='H_B_Curso1B_2', cat='Binary')
H_F_Curso1F_2 = LpVariable(name='H_F_Curso1F_2', cat='Binary')


#{Dia i}_{Franja j}_{cuatrimestre k}: El dia i (LUNES; MARTES, etc) en la franja horaria j en el cuatrimestre k se esta cursando

LUNES_1_1 = LpVariable(name='LUNES_1_1', cat='Binary')
LUNES_2_1 = LpVariable(name='LUNES_2_1', cat='Binary')
LUNES_3_1 = LpVariable(name='LUNES_3_1', cat='Binary')
LUNES_4_1 = LpVariable(name='LUNES_4_1', cat='Binary')
LUNES_5_1 = LpVariable(name='LUNES_5_1', cat='Binary')
LUNES_6_1 = LpVariable(name='LUNES_6_1', cat='Binary')
LUNES_7_1 = LpVariable(name='LUNES_7_1', cat='Binary')
LUNES_8_1 = LpVariable(name='LUNES_8_1', cat='Binary')
MARTES_1_1 = LpVariable(name='MARTES_1_1', cat='Binary')
MARTES_2_1 = LpVariable(name='MARTES_2_1', cat='Binary')
MARTES_3_1 = LpVariable(name='MARTES_3_1', cat='Binary')
MARTES_4_1 = LpVariable(name='MARTES_4_1', cat='Binary')
MARTES_5_1 = LpVariable(name='MARTES_5_1', cat='Binary')
MARTES_6_1 = LpVariable(name='MARTES_6_1', cat='Binary')
MARTES_7_1 = LpVariable(name='MARTES_7_1', cat='Binary')
MARTES_8_1 = LpVariable(name='MARTES_8_1', cat='Binary')
MIERCOLES_1_1 = LpVariable(name='MIERCOLES_1_1', cat='Binary')
MIERCOLES_2_1 = LpVariable(name='MIERCOLES_2_1', cat='Binary')
MIERCOLES_3_1 = LpVariable(name='MIERCOLES_3_1', cat='Binary')
MIERCOLES_4_1 = LpVariable(name='MIERCOLES_4_1', cat='Binary')
MIERCOLES_5_1 = LpVariable(name='MIERCOLES_5_1', cat='Binary')
MIERCOLES_6_1 = LpVariable(name='MIERCOLES_6_1', cat='Binary')
MIERCOLES_7_1 = LpVariable(name='MIERCOLES_7_1', cat='Binary')
MIERCOLES_8_1 = LpVariable(name='MIERCOLES_8_1', cat='Binary')
JUEVES_1_1 = LpVariable(name='JUEVES_1_1', cat='Binary')
JUEVES_2_1 = LpVariable(name='JUEVES_2_1', cat='Binary')
JUEVES_3_1 = LpVariable(name='JUEVES_3_1', cat='Binary')
JUEVES_4_1 = LpVariable(name='JUEVES_4_1', cat='Binary')
JUEVES_5_1 = LpVariable(name='JUEVES_5_1', cat='Binary')
JUEVES_6_1 = LpVariable(name='JUEVES_6_1', cat='Binary')
JUEVES_7_1 = LpVariable(name='JUEVES_7_1', cat='Binary')
JUEVES_8_1 = LpVariable(name='JUEVES_8_1', cat='Binary')
VIERNES_1_1 = LpVariable(name='VIERNES_1_1', cat='Binary')
VIERNES_2_1 = LpVariable(name='VIERNES_2_1', cat='Binary')
VIERNES_3_1 = LpVariable(name='VIERNES_3_1', cat='Binary')
VIERNES_4_1 = LpVariable(name='VIERNES_4_1', cat='Binary')
VIERNES_5_1 = LpVariable(name='VIERNES_5_1', cat='Binary')
VIERNES_6_1 = LpVariable(name='VIERNES_6_1', cat='Binary')
VIERNES_7_1 = LpVariable(name='VIERNES_7_1', cat='Binary')
VIERNES_8_1 = LpVariable(name='VIERNES_8_1', cat='Binary')
SABADO_1_1 = LpVariable(name='SABADO_1_1', cat='Binary')
SABADO_2_1 = LpVariable(name='SABADO_2_1', cat='Binary')
SABADO_3_1 = LpVariable(name='SABADO_3_1', cat='Binary')
SABADO_4_1 = LpVariable(name='SABADO_4_1', cat='Binary')
SABADO_5_1 = LpVariable(name='SABADO_5_1', cat='Binary')
SABADO_6_1 = LpVariable(name='SABADO_6_1', cat='Binary')
SABADO_7_1 = LpVariable(name='SABADO_7_1', cat='Binary')
SABADO_8_1 = LpVariable(name='SABADO_8_1', cat='Binary')
LUNES_1_2 = LpVariable(name='LUNES_1_2', cat='Binary')
LUNES_2_2 = LpVariable(name='LUNES_2_2', cat='Binary')
LUNES_3_2 = LpVariable(name='LUNES_3_2', cat='Binary')
LUNES_4_2 = LpVariable(name='LUNES_4_2', cat='Binary')
LUNES_5_2 = LpVariable(name='LUNES_5_2', cat='Binary')
LUNES_6_2 = LpVariable(name='LUNES_6_2', cat='Binary')
LUNES_7_2 = LpVariable(name='LUNES_7_2', cat='Binary')
LUNES_8_2 = LpVariable(name='LUNES_8_2', cat='Binary')
MARTES_1_2 = LpVariable(name='MARTES_1_2', cat='Binary')
MARTES_2_2 = LpVariable(name='MARTES_2_2', cat='Binary')
MARTES_3_2 = LpVariable(name='MARTES_3_2', cat='Binary')
MARTES_4_2 = LpVariable(name='MARTES_4_2', cat='Binary')
MARTES_5_2 = LpVariable(name='MARTES_5_2', cat='Binary')
MARTES_6_2 = LpVariable(name='MARTES_6_2', cat='Binary')
MARTES_7_2 = LpVariable(name='MARTES_7_2', cat='Binary')
MARTES_8_2 = LpVariable(name='MARTES_8_2', cat='Binary')
MIERCOLES_1_2 = LpVariable(name='MIERCOLES_1_2', cat='Binary')
MIERCOLES_2_2 = LpVariable(name='MIERCOLES_2_2', cat='Binary')
MIERCOLES_3_2 = LpVariable(name='MIERCOLES_3_2', cat='Binary')
MIERCOLES_4_2 = LpVariable(name='MIERCOLES_4_2', cat='Binary')
MIERCOLES_5_2 = LpVariable(name='MIERCOLES_5_2', cat='Binary')
MIERCOLES_6_2 = LpVariable(name='MIERCOLES_6_2', cat='Binary')
MIERCOLES_7_2 = LpVariable(name='MIERCOLES_7_2', cat='Binary')
MIERCOLES_8_2 = LpVariable(name='MIERCOLES_8_2', cat='Binary')
JUEVES_1_2 = LpVariable(name='JUEVES_1_2', cat='Binary')
JUEVES_2_2 = LpVariable(name='JUEVES_2_2', cat='Binary')
JUEVES_3_2 = LpVariable(name='JUEVES_3_2', cat='Binary')
JUEVES_4_2 = LpVariable(name='JUEVES_4_2', cat='Binary')
JUEVES_5_2 = LpVariable(name='JUEVES_5_2', cat='Binary')
JUEVES_6_2 = LpVariable(name='JUEVES_6_2', cat='Binary')
JUEVES_7_2 = LpVariable(name='JUEVES_7_2', cat='Binary')
JUEVES_8_2 = LpVariable(name='JUEVES_8_2', cat='Binary')
VIERNES_1_2 = LpVariable(name='VIERNES_1_2', cat='Binary')
VIERNES_2_2 = LpVariable(name='VIERNES_2_2', cat='Binary')
VIERNES_3_2 = LpVariable(name='VIERNES_3_2', cat='Binary')
VIERNES_4_2 = LpVariable(name='VIERNES_4_2', cat='Binary')
VIERNES_5_2 = LpVariable(name='VIERNES_5_2', cat='Binary')
VIERNES_6_2 = LpVariable(name='VIERNES_6_2', cat='Binary')
VIERNES_7_2 = LpVariable(name='VIERNES_7_2', cat='Binary')
VIERNES_8_2 = LpVariable(name='VIERNES_8_2', cat='Binary')
SABADO_1_2 = LpVariable(name='SABADO_1_2', cat='Binary')
SABADO_2_2 = LpVariable(name='SABADO_2_2', cat='Binary')
SABADO_3_2 = LpVariable(name='SABADO_3_2', cat='Binary')
SABADO_4_2 = LpVariable(name='SABADO_4_2', cat='Binary')
SABADO_5_2 = LpVariable(name='SABADO_5_2', cat='Binary')
SABADO_6_2 = LpVariable(name='SABADO_6_2', cat='Binary')
SABADO_7_2 = LpVariable(name='SABADO_7_2', cat='Binary')
SABADO_8_2 = LpVariable(name='SABADO_8_2', cat='Binary')


#R_{materia}_{nombre curso}_{dia}_{franja}_{cuatrimestre}: El horario para la materia y curso en ese cuatrimestre esta habilitado

R_H_Curso1H_JUEVES_5_1 = LpVariable(name='R_H_Curso1H_JUEVES_5_1', cat='Binary')
R_H_Curso1H_JUEVES_6_1 = LpVariable(name='R_H_Curso1H_JUEVES_6_1', cat='Binary')
R_D_Curso1D_MARTES_5_1 = LpVariable(name='R_D_Curso1D_MARTES_5_1', cat='Binary')
R_D_Curso1D_MARTES_6_1 = LpVariable(name='R_D_Curso1D_MARTES_6_1', cat='Binary')
R_I_Curso1I_VIERNES_1_1 = LpVariable(name='R_I_Curso1I_VIERNES_1_1', cat='Binary')
R_I_Curso1I_VIERNES_2_1 = LpVariable(name='R_I_Curso1I_VIERNES_2_1', cat='Binary')
R_C_Curso1C_MARTES_1_1 = LpVariable(name='R_C_Curso1C_MARTES_1_1', cat='Binary')
R_C_Curso1C_MARTES_2_1 = LpVariable(name='R_C_Curso1C_MARTES_2_1', cat='Binary')
R_E_Curso1E_MIERCOLES_1_1 = LpVariable(name='R_E_Curso1E_MIERCOLES_1_1', cat='Binary')
R_E_Curso1E_MIERCOLES_2_1 = LpVariable(name='R_E_Curso1E_MIERCOLES_2_1', cat='Binary')
R_J_Curso1J_SABADO_1_1 = LpVariable(name='R_J_Curso1J_SABADO_1_1', cat='Binary')
R_J_Curso1J_SABADO_2_1 = LpVariable(name='R_J_Curso1J_SABADO_2_1', cat='Binary')
R_A_Curso1A_LUNES_1_1 = LpVariable(name='R_A_Curso1A_LUNES_1_1', cat='Binary')
R_A_Curso1A_LUNES_2_1 = LpVariable(name='R_A_Curso1A_LUNES_2_1', cat='Binary')
R_G_Curso1G_MIERCOLES_5_1 = LpVariable(name='R_G_Curso1G_MIERCOLES_5_1', cat='Binary')
R_G_Curso1G_MIERCOLES_6_1 = LpVariable(name='R_G_Curso1G_MIERCOLES_6_1', cat='Binary')
R_B_Curso1B_LUNES_5_1 = LpVariable(name='R_B_Curso1B_LUNES_5_1', cat='Binary')
R_B_Curso1B_LUNES_6_1 = LpVariable(name='R_B_Curso1B_LUNES_6_1', cat='Binary')
R_F_Curso1F_JUEVES_1_1 = LpVariable(name='R_F_Curso1F_JUEVES_1_1', cat='Binary')
R_F_Curso1F_JUEVES_2_1 = LpVariable(name='R_F_Curso1F_JUEVES_2_1', cat='Binary')
R_H_Curso1H_JUEVES_5_2 = LpVariable(name='R_H_Curso1H_JUEVES_5_2', cat='Binary')
R_H_Curso1H_JUEVES_6_2 = LpVariable(name='R_H_Curso1H_JUEVES_6_2', cat='Binary')
R_D_Curso1D_MARTES_5_2 = LpVariable(name='R_D_Curso1D_MARTES_5_2', cat='Binary')
R_D_Curso1D_MARTES_6_2 = LpVariable(name='R_D_Curso1D_MARTES_6_2', cat='Binary')
R_I_Curso1I_VIERNES_1_2 = LpVariable(name='R_I_Curso1I_VIERNES_1_2', cat='Binary')
R_I_Curso1I_VIERNES_2_2 = LpVariable(name='R_I_Curso1I_VIERNES_2_2', cat='Binary')
R_C_Curso1C_MARTES_1_2 = LpVariable(name='R_C_Curso1C_MARTES_1_2', cat='Binary')
R_C_Curso1C_MARTES_2_2 = LpVariable(name='R_C_Curso1C_MARTES_2_2', cat='Binary')
R_E_Curso1E_MIERCOLES_1_2 = LpVariable(name='R_E_Curso1E_MIERCOLES_1_2', cat='Binary')
R_E_Curso1E_MIERCOLES_2_2 = LpVariable(name='R_E_Curso1E_MIERCOLES_2_2', cat='Binary')
R_J_Curso1J_SABADO_1_2 = LpVariable(name='R_J_Curso1J_SABADO_1_2', cat='Binary')
R_J_Curso1J_SABADO_2_2 = LpVariable(name='R_J_Curso1J_SABADO_2_2', cat='Binary')
R_A_Curso1A_LUNES_1_2 = LpVariable(name='R_A_Curso1A_LUNES_1_2', cat='Binary')
R_A_Curso1A_LUNES_2_2 = LpVariable(name='R_A_Curso1A_LUNES_2_2', cat='Binary')
R_G_Curso1G_MIERCOLES_5_2 = LpVariable(name='R_G_Curso1G_MIERCOLES_5_2', cat='Binary')
R_G_Curso1G_MIERCOLES_6_2 = LpVariable(name='R_G_Curso1G_MIERCOLES_6_2', cat='Binary')
R_B_Curso1B_LUNES_5_2 = LpVariable(name='R_B_Curso1B_LUNES_5_2', cat='Binary')
R_B_Curso1B_LUNES_6_2 = LpVariable(name='R_B_Curso1B_LUNES_6_2', cat='Binary')
R_F_Curso1F_JUEVES_1_2 = LpVariable(name='R_F_Curso1F_JUEVES_1_2', cat='Binary')
R_F_Curso1F_JUEVES_2_2 = LpVariable(name='R_F_Curso1F_JUEVES_2_2', cat='Binary')


#OCUPADO_{dia}_{cuatrimestre}: Vale 1 si el {dia} en el {cuatrimestre} tiene al menos un horario ocupado

OCUPADO_LUNES_1 = LpVariable(name='OCUPADO_LUNES_1', cat='Binary')
OCUPADO_MARTES_1 = LpVariable(name='OCUPADO_MARTES_1', cat='Binary')
OCUPADO_MIERCOLES_1 = LpVariable(name='OCUPADO_MIERCOLES_1', cat='Binary')
OCUPADO_JUEVES_1 = LpVariable(name='OCUPADO_JUEVES_1', cat='Binary')
OCUPADO_VIERNES_1 = LpVariable(name='OCUPADO_VIERNES_1', cat='Binary')
OCUPADO_SABADO_1 = LpVariable(name='OCUPADO_SABADO_1', cat='Binary')
OCUPADO_LUNES_2 = LpVariable(name='OCUPADO_LUNES_2', cat='Binary')
OCUPADO_MARTES_2 = LpVariable(name='OCUPADO_MARTES_2', cat='Binary')
OCUPADO_MIERCOLES_2 = LpVariable(name='OCUPADO_MIERCOLES_2', cat='Binary')
OCUPADO_JUEVES_2 = LpVariable(name='OCUPADO_JUEVES_2', cat='Binary')
OCUPADO_VIERNES_2 = LpVariable(name='OCUPADO_VIERNES_2', cat='Binary')
OCUPADO_SABADO_2 = LpVariable(name='OCUPADO_SABADO_2', cat='Binary')


#MAXIMA_FRANJA_{dia}_{cuatrimestre}: Numero de la maxima franja ocupada en el {dia} en el {cuatrimestre}.
#MINIMA_FRANJA_{dia}_{cuatrimestre}: Numero de la minima franja ocupada en el {dia} en el {cuatrimestre}.

MAXIMA_FRANJA_LUNES_1 = LpVariable(name='MAXIMA_FRANJA_LUNES_1', cat='Integer')
MINIMA_FRANJA_LUNES_1 = LpVariable(name='MINIMA_FRANJA_LUNES_1', cat='Integer')
MAXIMA_FRANJA_MARTES_1 = LpVariable(name='MAXIMA_FRANJA_MARTES_1', cat='Integer')
MINIMA_FRANJA_MARTES_1 = LpVariable(name='MINIMA_FRANJA_MARTES_1', cat='Integer')
MAXIMA_FRANJA_MIERCOLES_1 = LpVariable(name='MAXIMA_FRANJA_MIERCOLES_1', cat='Integer')
MINIMA_FRANJA_MIERCOLES_1 = LpVariable(name='MINIMA_FRANJA_MIERCOLES_1', cat='Integer')
MAXIMA_FRANJA_JUEVES_1 = LpVariable(name='MAXIMA_FRANJA_JUEVES_1', cat='Integer')
MINIMA_FRANJA_JUEVES_1 = LpVariable(name='MINIMA_FRANJA_JUEVES_1', cat='Integer')
MAXIMA_FRANJA_VIERNES_1 = LpVariable(name='MAXIMA_FRANJA_VIERNES_1', cat='Integer')
MINIMA_FRANJA_VIERNES_1 = LpVariable(name='MINIMA_FRANJA_VIERNES_1', cat='Integer')
MAXIMA_FRANJA_SABADO_1 = LpVariable(name='MAXIMA_FRANJA_SABADO_1', cat='Integer')
MINIMA_FRANJA_SABADO_1 = LpVariable(name='MINIMA_FRANJA_SABADO_1', cat='Integer')
MAXIMA_FRANJA_LUNES_2 = LpVariable(name='MAXIMA_FRANJA_LUNES_2', cat='Integer')
MINIMA_FRANJA_LUNES_2 = LpVariable(name='MINIMA_FRANJA_LUNES_2', cat='Integer')
MAXIMA_FRANJA_MARTES_2 = LpVariable(name='MAXIMA_FRANJA_MARTES_2', cat='Integer')
MINIMA_FRANJA_MARTES_2 = LpVariable(name='MINIMA_FRANJA_MARTES_2', cat='Integer')
MAXIMA_FRANJA_MIERCOLES_2 = LpVariable(name='MAXIMA_FRANJA_MIERCOLES_2', cat='Integer')
MINIMA_FRANJA_MIERCOLES_2 = LpVariable(name='MINIMA_FRANJA_MIERCOLES_2', cat='Integer')
MAXIMA_FRANJA_JUEVES_2 = LpVariable(name='MAXIMA_FRANJA_JUEVES_2', cat='Integer')
MINIMA_FRANJA_JUEVES_2 = LpVariable(name='MINIMA_FRANJA_JUEVES_2', cat='Integer')
MAXIMA_FRANJA_VIERNES_2 = LpVariable(name='MAXIMA_FRANJA_VIERNES_2', cat='Integer')
MINIMA_FRANJA_VIERNES_2 = LpVariable(name='MINIMA_FRANJA_VIERNES_2', cat='Integer')
MAXIMA_FRANJA_SABADO_2 = LpVariable(name='MAXIMA_FRANJA_SABADO_2', cat='Integer')
MINIMA_FRANJA_SABADO_2 = LpVariable(name='MINIMA_FRANJA_SABADO_2', cat='Integer')


#HORAS_LIBRES_{dia}_{cuatrimestre}: Cantidad de horas libres entre materias el {dia} en el {cuatrimestre}.

HORAS_LIBRES_LUNES_1 = LpVariable(name='HORAS_LIBRES_LUNES_1', cat='Integer')
HORAS_LIBRES_MARTES_1 = LpVariable(name='HORAS_LIBRES_MARTES_1', cat='Integer')
HORAS_LIBRES_MIERCOLES_1 = LpVariable(name='HORAS_LIBRES_MIERCOLES_1', cat='Integer')
HORAS_LIBRES_JUEVES_1 = LpVariable(name='HORAS_LIBRES_JUEVES_1', cat='Integer')
HORAS_LIBRES_VIERNES_1 = LpVariable(name='HORAS_LIBRES_VIERNES_1', cat='Integer')
HORAS_LIBRES_SABADO_1 = LpVariable(name='HORAS_LIBRES_SABADO_1', cat='Integer')
HORAS_LIBRES_LUNES_2 = LpVariable(name='HORAS_LIBRES_LUNES_2', cat='Integer')
HORAS_LIBRES_MARTES_2 = LpVariable(name='HORAS_LIBRES_MARTES_2', cat='Integer')
HORAS_LIBRES_MIERCOLES_2 = LpVariable(name='HORAS_LIBRES_MIERCOLES_2', cat='Integer')
HORAS_LIBRES_JUEVES_2 = LpVariable(name='HORAS_LIBRES_JUEVES_2', cat='Integer')
HORAS_LIBRES_VIERNES_2 = LpVariable(name='HORAS_LIBRES_VIERNES_2', cat='Integer')
HORAS_LIBRES_SABADO_2 = LpVariable(name='HORAS_LIBRES_SABADO_2', cat='Integer')


#HORAS_LIBRES_TOTALES: Cantidad de horas libres en todo el plan

HORAS_LIBRES_TOTALES = LpVariable(name='HORAS_LIBRES_TOTALES', cat='Integer')


# Definicion del problema

prob = LpProblem('Jenny_Calculo_plan_carrera', LpMinimize)


# La materia i se debe cursar en un unico cuatrimestre. Ademas, si es obligatoria, debe cursarse si o si.

prob += (Y_H_1 + Y_H_2 >= 1)
prob += (Y_H_1 + Y_H_2 <= 1)

prob += (Y_D_1 + Y_D_2 >= 1)
prob += (Y_D_1 + Y_D_2 <= 1)

prob += (Y_I_1 + Y_I_2 >= 1)
prob += (Y_I_1 + Y_I_2 <= 1)

prob += (Y_C_1 + Y_C_2 >= 1)
prob += (Y_C_1 + Y_C_2 <= 1)

prob += (Y_E_1 + Y_E_2 >= 1)
prob += (Y_E_1 + Y_E_2 <= 1)

prob += (Y_J_1 + Y_J_2 >= 1)
prob += (Y_J_1 + Y_J_2 <= 1)

prob += (Y_A_1 + Y_A_2 >= 1)
prob += (Y_A_1 + Y_A_2 <= 1)

prob += (Y_G_1 + Y_G_2 >= 1)
prob += (Y_G_1 + Y_G_2 <= 1)

prob += (Y_B_1 + Y_B_2 >= 1)
prob += (Y_B_1 + Y_B_2 <= 1)

prob += (Y_F_1 + Y_F_2 >= 1)
prob += (Y_F_1 + Y_F_2 <= 1)


# Numero de cuatrimestre en que es cursada la materia

prob += (1*Y_H_1 + 2*Y_H_2 - CH <= 0)
prob += (1*Y_H_1 + 2*Y_H_2 - CH >= 0)

prob += (1*Y_D_1 + 2*Y_D_2 - CD <= 0)
prob += (1*Y_D_1 + 2*Y_D_2 - CD >= 0)

prob += (1*Y_I_1 + 2*Y_I_2 - CI <= 0)
prob += (1*Y_I_1 + 2*Y_I_2 - CI >= 0)

prob += (1*Y_C_1 + 2*Y_C_2 - CC <= 0)
prob += (1*Y_C_1 + 2*Y_C_2 - CC >= 0)

prob += (1*Y_E_1 + 2*Y_E_2 - CE <= 0)
prob += (1*Y_E_1 + 2*Y_E_2 - CE >= 0)

prob += (1*Y_J_1 + 2*Y_J_2 - CJ <= 0)
prob += (1*Y_J_1 + 2*Y_J_2 - CJ >= 0)

prob += (1*Y_A_1 + 2*Y_A_2 - CA <= 0)
prob += (1*Y_A_1 + 2*Y_A_2 - CA >= 0)

prob += (1*Y_G_1 + 2*Y_G_2 - CG <= 0)
prob += (1*Y_G_1 + 2*Y_G_2 - CG >= 0)

prob += (1*Y_B_1 + 2*Y_B_2 - CB <= 0)
prob += (1*Y_B_1 + 2*Y_B_2 - CB >= 0)

prob += (1*Y_F_1 + 2*Y_F_2 - CF <= 0)
prob += (1*Y_F_1 + 2*Y_F_2 - CF >= 0)


# Los cuatrimestres de las correlativas deben ser menores

prob += (CF - CD >= 1)
prob += (CF - CC >= 1)
prob += (CH - CE >= 1)
prob += (CH - CA >= 1)
prob += (CE - CB >= 1)
prob += (CG - CF >= 1)


# La cantidad de materias por cuatrimestre no puede superar un valor maximo

prob += (Y_H_1 + Y_D_1 + Y_I_1 + Y_C_1 + Y_E_1 + Y_J_1 + Y_A_1 + Y_G_1 + Y_B_1 + Y_F_1 <= 2)
prob += (Y_H_2 + Y_D_2 + Y_I_2 + Y_C_2 + Y_E_2 + Y_J_2 + Y_A_2 + Y_G_2 + Y_B_2 + Y_F_2 <= 2)


#TOTAL_CUATRIMESTRES es el maximo de los Ci

prob += (TOTAL_CUATRIMESTRES >= 0)

prob += (CH <= TOTAL_CUATRIMESTRES)
prob += (-CH <= TOTAL_CUATRIMESTRES)

prob += (CD <= TOTAL_CUATRIMESTRES)
prob += (-CD <= TOTAL_CUATRIMESTRES)

prob += (CI <= TOTAL_CUATRIMESTRES)
prob += (-CI <= TOTAL_CUATRIMESTRES)

prob += (CC <= TOTAL_CUATRIMESTRES)
prob += (-CC <= TOTAL_CUATRIMESTRES)

prob += (CE <= TOTAL_CUATRIMESTRES)
prob += (-CE <= TOTAL_CUATRIMESTRES)

prob += (CJ <= TOTAL_CUATRIMESTRES)
prob += (-CJ <= TOTAL_CUATRIMESTRES)

prob += (CA <= TOTAL_CUATRIMESTRES)
prob += (-CA <= TOTAL_CUATRIMESTRES)

prob += (CG <= TOTAL_CUATRIMESTRES)
prob += (-CG <= TOTAL_CUATRIMESTRES)

prob += (CB <= TOTAL_CUATRIMESTRES)
prob += (-CB <= TOTAL_CUATRIMESTRES)

prob += (CF <= TOTAL_CUATRIMESTRES)
prob += (-CF <= TOTAL_CUATRIMESTRES)


# Calculo de creditos al terminar cada cuatrimestre

prob += (CRED0 <= 0)
prob += (CRED0 >= 0)
prob += (1*Y_H_1 + 1*Y_D_1 + 1*Y_I_1 + 1*Y_C_1 + 1*Y_E_1 + 1*Y_J_1 + 1*Y_A_1 + 1*Y_G_1 + 1*Y_B_1 + 1*Y_F_1 + CRED0 - CRED1 <= 0)
prob += (1*Y_H_1 + 1*Y_D_1 + 1*Y_I_1 + 1*Y_C_1 + 1*Y_E_1 + 1*Y_J_1 + 1*Y_A_1 + 1*Y_G_1 + 1*Y_B_1 + 1*Y_F_1 + CRED0 - CRED1 >= 0)

# Restricciones sobre aquellas materias que requieren creditos minimos para poder cursar


#Si la materia se cursa en ese cuatrimestre en ese curso en particular, entonces se debn cursar todos los horarios del mismo

prob += (H_H_Curso1H_1 <= R_H_Curso1H_JUEVES_5_1)
prob += (H_H_Curso1H_1 >= R_H_Curso1H_JUEVES_5_1)
prob += (H_H_Curso1H_1 <= R_H_Curso1H_JUEVES_6_1)
prob += (H_H_Curso1H_1 >= R_H_Curso1H_JUEVES_6_1)
prob += (R_H_Curso1H_JUEVES_5_1 <= R_H_Curso1H_JUEVES_6_1)
prob += (R_H_Curso1H_JUEVES_5_1 >= R_H_Curso1H_JUEVES_6_1)

prob += (H_D_Curso1D_1 <= R_D_Curso1D_MARTES_5_1)
prob += (H_D_Curso1D_1 >= R_D_Curso1D_MARTES_5_1)
prob += (H_D_Curso1D_1 <= R_D_Curso1D_MARTES_6_1)
prob += (H_D_Curso1D_1 >= R_D_Curso1D_MARTES_6_1)
prob += (R_D_Curso1D_MARTES_5_1 <= R_D_Curso1D_MARTES_6_1)
prob += (R_D_Curso1D_MARTES_5_1 >= R_D_Curso1D_MARTES_6_1)

prob += (H_I_Curso1I_1 <= R_I_Curso1I_VIERNES_1_1)
prob += (H_I_Curso1I_1 >= R_I_Curso1I_VIERNES_1_1)
prob += (H_I_Curso1I_1 <= R_I_Curso1I_VIERNES_2_1)
prob += (H_I_Curso1I_1 >= R_I_Curso1I_VIERNES_2_1)
prob += (R_I_Curso1I_VIERNES_1_1 <= R_I_Curso1I_VIERNES_2_1)
prob += (R_I_Curso1I_VIERNES_1_1 >= R_I_Curso1I_VIERNES_2_1)

prob += (H_C_Curso1C_1 <= R_C_Curso1C_MARTES_1_1)
prob += (H_C_Curso1C_1 >= R_C_Curso1C_MARTES_1_1)
prob += (H_C_Curso1C_1 <= R_C_Curso1C_MARTES_2_1)
prob += (H_C_Curso1C_1 >= R_C_Curso1C_MARTES_2_1)
prob += (R_C_Curso1C_MARTES_1_1 <= R_C_Curso1C_MARTES_2_1)
prob += (R_C_Curso1C_MARTES_1_1 >= R_C_Curso1C_MARTES_2_1)

prob += (H_E_Curso1E_1 <= R_E_Curso1E_MIERCOLES_1_1)
prob += (H_E_Curso1E_1 >= R_E_Curso1E_MIERCOLES_1_1)
prob += (H_E_Curso1E_1 <= R_E_Curso1E_MIERCOLES_2_1)
prob += (H_E_Curso1E_1 >= R_E_Curso1E_MIERCOLES_2_1)
prob += (R_E_Curso1E_MIERCOLES_1_1 <= R_E_Curso1E_MIERCOLES_2_1)
prob += (R_E_Curso1E_MIERCOLES_1_1 >= R_E_Curso1E_MIERCOLES_2_1)

prob += (H_J_Curso1J_1 <= R_J_Curso1J_SABADO_1_1)
prob += (H_J_Curso1J_1 >= R_J_Curso1J_SABADO_1_1)
prob += (H_J_Curso1J_1 <= R_J_Curso1J_SABADO_2_1)
prob += (H_J_Curso1J_1 >= R_J_Curso1J_SABADO_2_1)
prob += (R_J_Curso1J_SABADO_1_1 <= R_J_Curso1J_SABADO_2_1)
prob += (R_J_Curso1J_SABADO_1_1 >= R_J_Curso1J_SABADO_2_1)

prob += (H_A_Curso1A_1 <= R_A_Curso1A_LUNES_1_1)
prob += (H_A_Curso1A_1 >= R_A_Curso1A_LUNES_1_1)
prob += (H_A_Curso1A_1 <= R_A_Curso1A_LUNES_2_1)
prob += (H_A_Curso1A_1 >= R_A_Curso1A_LUNES_2_1)
prob += (R_A_Curso1A_LUNES_1_1 <= R_A_Curso1A_LUNES_2_1)
prob += (R_A_Curso1A_LUNES_1_1 >= R_A_Curso1A_LUNES_2_1)

prob += (H_G_Curso1G_1 <= R_G_Curso1G_MIERCOLES_5_1)
prob += (H_G_Curso1G_1 >= R_G_Curso1G_MIERCOLES_5_1)
prob += (H_G_Curso1G_1 <= R_G_Curso1G_MIERCOLES_6_1)
prob += (H_G_Curso1G_1 >= R_G_Curso1G_MIERCOLES_6_1)
prob += (R_G_Curso1G_MIERCOLES_5_1 <= R_G_Curso1G_MIERCOLES_6_1)
prob += (R_G_Curso1G_MIERCOLES_5_1 >= R_G_Curso1G_MIERCOLES_6_1)

prob += (H_B_Curso1B_1 <= R_B_Curso1B_LUNES_5_1)
prob += (H_B_Curso1B_1 >= R_B_Curso1B_LUNES_5_1)
prob += (H_B_Curso1B_1 <= R_B_Curso1B_LUNES_6_1)
prob += (H_B_Curso1B_1 >= R_B_Curso1B_LUNES_6_1)
prob += (R_B_Curso1B_LUNES_5_1 <= R_B_Curso1B_LUNES_6_1)
prob += (R_B_Curso1B_LUNES_5_1 >= R_B_Curso1B_LUNES_6_1)

prob += (H_F_Curso1F_1 <= R_F_Curso1F_JUEVES_1_1)
prob += (H_F_Curso1F_1 >= R_F_Curso1F_JUEVES_1_1)
prob += (H_F_Curso1F_1 <= R_F_Curso1F_JUEVES_2_1)
prob += (H_F_Curso1F_1 >= R_F_Curso1F_JUEVES_2_1)
prob += (R_F_Curso1F_JUEVES_1_1 <= R_F_Curso1F_JUEVES_2_1)
prob += (R_F_Curso1F_JUEVES_1_1 >= R_F_Curso1F_JUEVES_2_1)

prob += (H_H_Curso1H_2 <= R_H_Curso1H_JUEVES_5_2)
prob += (H_H_Curso1H_2 >= R_H_Curso1H_JUEVES_5_2)
prob += (H_H_Curso1H_2 <= R_H_Curso1H_JUEVES_6_2)
prob += (H_H_Curso1H_2 >= R_H_Curso1H_JUEVES_6_2)
prob += (R_H_Curso1H_JUEVES_5_2 <= R_H_Curso1H_JUEVES_6_2)
prob += (R_H_Curso1H_JUEVES_5_2 >= R_H_Curso1H_JUEVES_6_2)

prob += (H_D_Curso1D_2 <= R_D_Curso1D_MARTES_5_2)
prob += (H_D_Curso1D_2 >= R_D_Curso1D_MARTES_5_2)
prob += (H_D_Curso1D_2 <= R_D_Curso1D_MARTES_6_2)
prob += (H_D_Curso1D_2 >= R_D_Curso1D_MARTES_6_2)
prob += (R_D_Curso1D_MARTES_5_2 <= R_D_Curso1D_MARTES_6_2)
prob += (R_D_Curso1D_MARTES_5_2 >= R_D_Curso1D_MARTES_6_2)

prob += (H_I_Curso1I_2 <= R_I_Curso1I_VIERNES_1_2)
prob += (H_I_Curso1I_2 >= R_I_Curso1I_VIERNES_1_2)
prob += (H_I_Curso1I_2 <= R_I_Curso1I_VIERNES_2_2)
prob += (H_I_Curso1I_2 >= R_I_Curso1I_VIERNES_2_2)
prob += (R_I_Curso1I_VIERNES_1_2 <= R_I_Curso1I_VIERNES_2_2)
prob += (R_I_Curso1I_VIERNES_1_2 >= R_I_Curso1I_VIERNES_2_2)

prob += (H_C_Curso1C_2 <= R_C_Curso1C_MARTES_1_2)
prob += (H_C_Curso1C_2 >= R_C_Curso1C_MARTES_1_2)
prob += (H_C_Curso1C_2 <= R_C_Curso1C_MARTES_2_2)
prob += (H_C_Curso1C_2 >= R_C_Curso1C_MARTES_2_2)
prob += (R_C_Curso1C_MARTES_1_2 <= R_C_Curso1C_MARTES_2_2)
prob += (R_C_Curso1C_MARTES_1_2 >= R_C_Curso1C_MARTES_2_2)

prob += (H_E_Curso1E_2 <= R_E_Curso1E_MIERCOLES_1_2)
prob += (H_E_Curso1E_2 >= R_E_Curso1E_MIERCOLES_1_2)
prob += (H_E_Curso1E_2 <= R_E_Curso1E_MIERCOLES_2_2)
prob += (H_E_Curso1E_2 >= R_E_Curso1E_MIERCOLES_2_2)
prob += (R_E_Curso1E_MIERCOLES_1_2 <= R_E_Curso1E_MIERCOLES_2_2)
prob += (R_E_Curso1E_MIERCOLES_1_2 >= R_E_Curso1E_MIERCOLES_2_2)

prob += (H_J_Curso1J_2 <= R_J_Curso1J_SABADO_1_2)
prob += (H_J_Curso1J_2 >= R_J_Curso1J_SABADO_1_2)
prob += (H_J_Curso1J_2 <= R_J_Curso1J_SABADO_2_2)
prob += (H_J_Curso1J_2 >= R_J_Curso1J_SABADO_2_2)
prob += (R_J_Curso1J_SABADO_1_2 <= R_J_Curso1J_SABADO_2_2)
prob += (R_J_Curso1J_SABADO_1_2 >= R_J_Curso1J_SABADO_2_2)

prob += (H_A_Curso1A_2 <= R_A_Curso1A_LUNES_1_2)
prob += (H_A_Curso1A_2 >= R_A_Curso1A_LUNES_1_2)
prob += (H_A_Curso1A_2 <= R_A_Curso1A_LUNES_2_2)
prob += (H_A_Curso1A_2 >= R_A_Curso1A_LUNES_2_2)
prob += (R_A_Curso1A_LUNES_1_2 <= R_A_Curso1A_LUNES_2_2)
prob += (R_A_Curso1A_LUNES_1_2 >= R_A_Curso1A_LUNES_2_2)

prob += (H_G_Curso1G_2 <= R_G_Curso1G_MIERCOLES_5_2)
prob += (H_G_Curso1G_2 >= R_G_Curso1G_MIERCOLES_5_2)
prob += (H_G_Curso1G_2 <= R_G_Curso1G_MIERCOLES_6_2)
prob += (H_G_Curso1G_2 >= R_G_Curso1G_MIERCOLES_6_2)
prob += (R_G_Curso1G_MIERCOLES_5_2 <= R_G_Curso1G_MIERCOLES_6_2)
prob += (R_G_Curso1G_MIERCOLES_5_2 >= R_G_Curso1G_MIERCOLES_6_2)

prob += (H_B_Curso1B_2 <= R_B_Curso1B_LUNES_5_2)
prob += (H_B_Curso1B_2 >= R_B_Curso1B_LUNES_5_2)
prob += (H_B_Curso1B_2 <= R_B_Curso1B_LUNES_6_2)
prob += (H_B_Curso1B_2 >= R_B_Curso1B_LUNES_6_2)
prob += (R_B_Curso1B_LUNES_5_2 <= R_B_Curso1B_LUNES_6_2)
prob += (R_B_Curso1B_LUNES_5_2 >= R_B_Curso1B_LUNES_6_2)

prob += (H_F_Curso1F_2 <= R_F_Curso1F_JUEVES_1_2)
prob += (H_F_Curso1F_2 >= R_F_Curso1F_JUEVES_1_2)
prob += (H_F_Curso1F_2 <= R_F_Curso1F_JUEVES_2_2)
prob += (H_F_Curso1F_2 >= R_F_Curso1F_JUEVES_2_2)
prob += (R_F_Curso1F_JUEVES_1_2 <= R_F_Curso1F_JUEVES_2_2)
prob += (R_F_Curso1F_JUEVES_1_2 >= R_F_Curso1F_JUEVES_2_2)


#No hay giratiempos: Solo puede cursarse una materia en un unico curso en el mismo horario

prob += (LUNES_1_1 <= R_A_Curso1A_LUNES_1_1)
prob += (LUNES_1_1 >= R_A_Curso1A_LUNES_1_1)
prob += (LUNES_2_1 <= R_A_Curso1A_LUNES_2_1)
prob += (LUNES_2_1 >= R_A_Curso1A_LUNES_2_1)
prob += (LUNES_3_1 <= 0)
prob += (LUNES_3_1 >= 0)
prob += (LUNES_4_1 <= 0)
prob += (LUNES_4_1 >= 0)
prob += (LUNES_5_1 <= R_B_Curso1B_LUNES_5_1)
prob += (LUNES_5_1 >= R_B_Curso1B_LUNES_5_1)
prob += (LUNES_6_1 <= R_B_Curso1B_LUNES_6_1)
prob += (LUNES_6_1 >= R_B_Curso1B_LUNES_6_1)
prob += (LUNES_7_1 <= 0)
prob += (LUNES_7_1 >= 0)
prob += (LUNES_8_1 <= 0)
prob += (LUNES_8_1 >= 0)
prob += (MARTES_1_1 <= R_C_Curso1C_MARTES_1_1)
prob += (MARTES_1_1 >= R_C_Curso1C_MARTES_1_1)
prob += (MARTES_2_1 <= R_C_Curso1C_MARTES_2_1)
prob += (MARTES_2_1 >= R_C_Curso1C_MARTES_2_1)
prob += (MARTES_3_1 <= 0)
prob += (MARTES_3_1 >= 0)
prob += (MARTES_4_1 <= 0)
prob += (MARTES_4_1 >= 0)
prob += (MARTES_5_1 <= R_D_Curso1D_MARTES_5_1)
prob += (MARTES_5_1 >= R_D_Curso1D_MARTES_5_1)
prob += (MARTES_6_1 <= R_D_Curso1D_MARTES_6_1)
prob += (MARTES_6_1 >= R_D_Curso1D_MARTES_6_1)
prob += (MARTES_7_1 <= 0)
prob += (MARTES_7_1 >= 0)
prob += (MARTES_8_1 <= 0)
prob += (MARTES_8_1 >= 0)
prob += (MIERCOLES_1_1 <= R_E_Curso1E_MIERCOLES_1_1)
prob += (MIERCOLES_1_1 >= R_E_Curso1E_MIERCOLES_1_1)
prob += (MIERCOLES_2_1 <= R_E_Curso1E_MIERCOLES_2_1)
prob += (MIERCOLES_2_1 >= R_E_Curso1E_MIERCOLES_2_1)
prob += (MIERCOLES_3_1 <= 0)
prob += (MIERCOLES_3_1 >= 0)
prob += (MIERCOLES_4_1 <= 0)
prob += (MIERCOLES_4_1 >= 0)
prob += (MIERCOLES_5_1 <= R_G_Curso1G_MIERCOLES_5_1)
prob += (MIERCOLES_5_1 >= R_G_Curso1G_MIERCOLES_5_1)
prob += (MIERCOLES_6_1 <= R_G_Curso1G_MIERCOLES_6_1)
prob += (MIERCOLES_6_1 >= R_G_Curso1G_MIERCOLES_6_1)
prob += (MIERCOLES_7_1 <= 0)
prob += (MIERCOLES_7_1 >= 0)
prob += (MIERCOLES_8_1 <= 0)
prob += (MIERCOLES_8_1 >= 0)
prob += (JUEVES_1_1 <= R_F_Curso1F_JUEVES_1_1)
prob += (JUEVES_1_1 >= R_F_Curso1F_JUEVES_1_1)
prob += (JUEVES_2_1 <= R_F_Curso1F_JUEVES_2_1)
prob += (JUEVES_2_1 >= R_F_Curso1F_JUEVES_2_1)
prob += (JUEVES_3_1 <= 0)
prob += (JUEVES_3_1 >= 0)
prob += (JUEVES_4_1 <= 0)
prob += (JUEVES_4_1 >= 0)
prob += (JUEVES_5_1 <= R_H_Curso1H_JUEVES_5_1)
prob += (JUEVES_5_1 >= R_H_Curso1H_JUEVES_5_1)
prob += (JUEVES_6_1 <= R_H_Curso1H_JUEVES_6_1)
prob += (JUEVES_6_1 >= R_H_Curso1H_JUEVES_6_1)
prob += (JUEVES_7_1 <= 0)
prob += (JUEVES_7_1 >= 0)
prob += (JUEVES_8_1 <= 0)
prob += (JUEVES_8_1 >= 0)
prob += (VIERNES_1_1 <= R_I_Curso1I_VIERNES_1_1)
prob += (VIERNES_1_1 >= R_I_Curso1I_VIERNES_1_1)
prob += (VIERNES_2_1 <= R_I_Curso1I_VIERNES_2_1)
prob += (VIERNES_2_1 >= R_I_Curso1I_VIERNES_2_1)
prob += (VIERNES_3_1 <= 0)
prob += (VIERNES_3_1 >= 0)
prob += (VIERNES_4_1 <= 0)
prob += (VIERNES_4_1 >= 0)
prob += (VIERNES_5_1 <= 0)
prob += (VIERNES_5_1 >= 0)
prob += (VIERNES_6_1 <= 0)
prob += (VIERNES_6_1 >= 0)
prob += (VIERNES_7_1 <= 0)
prob += (VIERNES_7_1 >= 0)
prob += (VIERNES_8_1 <= 0)
prob += (VIERNES_8_1 >= 0)
prob += (SABADO_1_1 <= R_J_Curso1J_SABADO_1_1)
prob += (SABADO_1_1 >= R_J_Curso1J_SABADO_1_1)
prob += (SABADO_2_1 <= R_J_Curso1J_SABADO_2_1)
prob += (SABADO_2_1 >= R_J_Curso1J_SABADO_2_1)
prob += (SABADO_3_1 <= 0)
prob += (SABADO_3_1 >= 0)
prob += (SABADO_4_1 <= 0)
prob += (SABADO_4_1 >= 0)
prob += (SABADO_5_1 <= 0)
prob += (SABADO_5_1 >= 0)
prob += (SABADO_6_1 <= 0)
prob += (SABADO_6_1 >= 0)
prob += (SABADO_7_1 <= 0)
prob += (SABADO_7_1 >= 0)
prob += (SABADO_8_1 <= 0)
prob += (SABADO_8_1 >= 0)
prob += (LUNES_1_2 <= R_A_Curso1A_LUNES_1_2)
prob += (LUNES_1_2 >= R_A_Curso1A_LUNES_1_2)
prob += (LUNES_2_2 <= R_A_Curso1A_LUNES_2_2)
prob += (LUNES_2_2 >= R_A_Curso1A_LUNES_2_2)
prob += (LUNES_3_2 <= 0)
prob += (LUNES_3_2 >= 0)
prob += (LUNES_4_2 <= 0)
prob += (LUNES_4_2 >= 0)
prob += (LUNES_5_2 <= R_B_Curso1B_LUNES_5_2)
prob += (LUNES_5_2 >= R_B_Curso1B_LUNES_5_2)
prob += (LUNES_6_2 <= R_B_Curso1B_LUNES_6_2)
prob += (LUNES_6_2 >= R_B_Curso1B_LUNES_6_2)
prob += (LUNES_7_2 <= 0)
prob += (LUNES_7_2 >= 0)
prob += (LUNES_8_2 <= 0)
prob += (LUNES_8_2 >= 0)
prob += (MARTES_1_2 <= R_C_Curso1C_MARTES_1_2)
prob += (MARTES_1_2 >= R_C_Curso1C_MARTES_1_2)
prob += (MARTES_2_2 <= R_C_Curso1C_MARTES_2_2)
prob += (MARTES_2_2 >= R_C_Curso1C_MARTES_2_2)
prob += (MARTES_3_2 <= 0)
prob += (MARTES_3_2 >= 0)
prob += (MARTES_4_2 <= 0)
prob += (MARTES_4_2 >= 0)
prob += (MARTES_5_2 <= R_D_Curso1D_MARTES_5_2)
prob += (MARTES_5_2 >= R_D_Curso1D_MARTES_5_2)
prob += (MARTES_6_2 <= R_D_Curso1D_MARTES_6_2)
prob += (MARTES_6_2 >= R_D_Curso1D_MARTES_6_2)
prob += (MARTES_7_2 <= 0)
prob += (MARTES_7_2 >= 0)
prob += (MARTES_8_2 <= 0)
prob += (MARTES_8_2 >= 0)
prob += (MIERCOLES_1_2 <= R_E_Curso1E_MIERCOLES_1_2)
prob += (MIERCOLES_1_2 >= R_E_Curso1E_MIERCOLES_1_2)
prob += (MIERCOLES_2_2 <= R_E_Curso1E_MIERCOLES_2_2)
prob += (MIERCOLES_2_2 >= R_E_Curso1E_MIERCOLES_2_2)
prob += (MIERCOLES_3_2 <= 0)
prob += (MIERCOLES_3_2 >= 0)
prob += (MIERCOLES_4_2 <= 0)
prob += (MIERCOLES_4_2 >= 0)
prob += (MIERCOLES_5_2 <= R_G_Curso1G_MIERCOLES_5_2)
prob += (MIERCOLES_5_2 >= R_G_Curso1G_MIERCOLES_5_2)
prob += (MIERCOLES_6_2 <= R_G_Curso1G_MIERCOLES_6_2)
prob += (MIERCOLES_6_2 >= R_G_Curso1G_MIERCOLES_6_2)
prob += (MIERCOLES_7_2 <= 0)
prob += (MIERCOLES_7_2 >= 0)
prob += (MIERCOLES_8_2 <= 0)
prob += (MIERCOLES_8_2 >= 0)
prob += (JUEVES_1_2 <= R_F_Curso1F_JUEVES_1_2)
prob += (JUEVES_1_2 >= R_F_Curso1F_JUEVES_1_2)
prob += (JUEVES_2_2 <= R_F_Curso1F_JUEVES_2_2)
prob += (JUEVES_2_2 >= R_F_Curso1F_JUEVES_2_2)
prob += (JUEVES_3_2 <= 0)
prob += (JUEVES_3_2 >= 0)
prob += (JUEVES_4_2 <= 0)
prob += (JUEVES_4_2 >= 0)
prob += (JUEVES_5_2 <= R_H_Curso1H_JUEVES_5_2)
prob += (JUEVES_5_2 >= R_H_Curso1H_JUEVES_5_2)
prob += (JUEVES_6_2 <= R_H_Curso1H_JUEVES_6_2)
prob += (JUEVES_6_2 >= R_H_Curso1H_JUEVES_6_2)
prob += (JUEVES_7_2 <= 0)
prob += (JUEVES_7_2 >= 0)
prob += (JUEVES_8_2 <= 0)
prob += (JUEVES_8_2 >= 0)
prob += (VIERNES_1_2 <= R_I_Curso1I_VIERNES_1_2)
prob += (VIERNES_1_2 >= R_I_Curso1I_VIERNES_1_2)
prob += (VIERNES_2_2 <= R_I_Curso1I_VIERNES_2_2)
prob += (VIERNES_2_2 >= R_I_Curso1I_VIERNES_2_2)
prob += (VIERNES_3_2 <= 0)
prob += (VIERNES_3_2 >= 0)
prob += (VIERNES_4_2 <= 0)
prob += (VIERNES_4_2 >= 0)
prob += (VIERNES_5_2 <= 0)
prob += (VIERNES_5_2 >= 0)
prob += (VIERNES_6_2 <= 0)
prob += (VIERNES_6_2 >= 0)
prob += (VIERNES_7_2 <= 0)
prob += (VIERNES_7_2 >= 0)
prob += (VIERNES_8_2 <= 0)
prob += (VIERNES_8_2 >= 0)
prob += (SABADO_1_2 <= R_J_Curso1J_SABADO_1_2)
prob += (SABADO_1_2 >= R_J_Curso1J_SABADO_1_2)
prob += (SABADO_2_2 <= R_J_Curso1J_SABADO_2_2)
prob += (SABADO_2_2 >= R_J_Curso1J_SABADO_2_2)
prob += (SABADO_3_2 <= 0)
prob += (SABADO_3_2 >= 0)
prob += (SABADO_4_2 <= 0)
prob += (SABADO_4_2 >= 0)
prob += (SABADO_5_2 <= 0)
prob += (SABADO_5_2 >= 0)
prob += (SABADO_6_2 <= 0)
prob += (SABADO_6_2 >= 0)
prob += (SABADO_7_2 <= 0)
prob += (SABADO_7_2 >= 0)
prob += (SABADO_8_2 <= 0)
prob += (SABADO_8_2 >= 0)

# Si la materia no se cursa ese cuatrimestre, entonces no puede cursarse en ninguno de los cursos de ese cuatrimestre

prob += (Y_H_1 >= H_H_Curso1H_1)
prob += (Y_D_1 >= H_D_Curso1D_1)
prob += (Y_I_1 >= H_I_Curso1I_1)
prob += (Y_C_1 >= H_C_Curso1C_1)
prob += (Y_E_1 >= H_E_Curso1E_1)
prob += (Y_J_1 >= H_J_Curso1J_1)
prob += (Y_A_1 >= H_A_Curso1A_1)
prob += (Y_G_1 >= H_G_Curso1G_1)
prob += (Y_B_1 >= H_B_Curso1B_1)
prob += (Y_F_1 >= H_F_Curso1F_1)
prob += (Y_H_2 >= H_H_Curso1H_2)
prob += (Y_D_2 >= H_D_Curso1D_2)
prob += (Y_I_2 >= H_I_Curso1I_2)
prob += (Y_C_2 >= H_C_Curso1C_2)
prob += (Y_E_2 >= H_E_Curso1E_2)
prob += (Y_J_2 >= H_J_Curso1J_2)
prob += (Y_A_2 >= H_A_Curso1A_2)
prob += (Y_G_2 >= H_G_Curso1G_2)
prob += (Y_B_2 >= H_B_Curso1B_2)
prob += (Y_F_2 >= H_F_Curso1F_2)

# La materia no puede cursarse en mas de un curso en el cuatrimestre

prob += (Y_H_1 <= H_H_Curso1H_1)
prob += (Y_D_1 <= H_D_Curso1D_1)
prob += (Y_I_1 <= H_I_Curso1I_1)
prob += (Y_C_1 <= H_C_Curso1C_1)
prob += (Y_E_1 <= H_E_Curso1E_1)
prob += (Y_J_1 <= H_J_Curso1J_1)
prob += (Y_A_1 <= H_A_Curso1A_1)
prob += (Y_G_1 <= H_G_Curso1G_1)
prob += (Y_B_1 <= H_B_Curso1B_1)
prob += (Y_F_1 <= H_F_Curso1F_1)
prob += (Y_H_2 <= H_H_Curso1H_2)
prob += (Y_D_2 <= H_D_Curso1D_2)
prob += (Y_I_2 <= H_I_Curso1I_2)
prob += (Y_C_2 <= H_C_Curso1C_2)
prob += (Y_E_2 <= H_E_Curso1E_2)
prob += (Y_J_2 <= H_J_Curso1J_2)
prob += (Y_A_2 <= H_A_Curso1A_2)
prob += (Y_G_2 <= H_G_Curso1G_2)
prob += (Y_B_2 <= H_B_Curso1B_2)
prob += (Y_F_2 <= H_F_Curso1F_2)

#Numero de franja horaria mayor por dia por cuatrimestre

prob += (MAXIMA_FRANJA_LUNES_1 >= 1 * LUNES_1_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 2 * LUNES_2_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 3 * LUNES_3_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 4 * LUNES_4_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 5 * LUNES_5_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 6 * LUNES_6_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 7 * LUNES_7_1 )
prob += (MAXIMA_FRANJA_LUNES_1 >= 8 * LUNES_8_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 1 * MARTES_1_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 2 * MARTES_2_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 3 * MARTES_3_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 4 * MARTES_4_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 5 * MARTES_5_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 6 * MARTES_6_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 7 * MARTES_7_1 )
prob += (MAXIMA_FRANJA_MARTES_1 >= 8 * MARTES_8_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 1 * MIERCOLES_1_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 2 * MIERCOLES_2_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 3 * MIERCOLES_3_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 4 * MIERCOLES_4_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 5 * MIERCOLES_5_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 6 * MIERCOLES_6_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 7 * MIERCOLES_7_1 )
prob += (MAXIMA_FRANJA_MIERCOLES_1 >= 8 * MIERCOLES_8_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 1 * JUEVES_1_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 2 * JUEVES_2_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 3 * JUEVES_3_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 4 * JUEVES_4_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 5 * JUEVES_5_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 6 * JUEVES_6_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 7 * JUEVES_7_1 )
prob += (MAXIMA_FRANJA_JUEVES_1 >= 8 * JUEVES_8_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 1 * VIERNES_1_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 2 * VIERNES_2_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 3 * VIERNES_3_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 4 * VIERNES_4_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 5 * VIERNES_5_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 6 * VIERNES_6_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 7 * VIERNES_7_1 )
prob += (MAXIMA_FRANJA_VIERNES_1 >= 8 * VIERNES_8_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 1 * SABADO_1_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 2 * SABADO_2_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 3 * SABADO_3_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 4 * SABADO_4_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 5 * SABADO_5_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 6 * SABADO_6_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 7 * SABADO_7_1 )
prob += (MAXIMA_FRANJA_SABADO_1 >= 8 * SABADO_8_1 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 1 * LUNES_1_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 2 * LUNES_2_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 3 * LUNES_3_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 4 * LUNES_4_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 5 * LUNES_5_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 6 * LUNES_6_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 7 * LUNES_7_2 )
prob += (MAXIMA_FRANJA_LUNES_2 >= 8 * LUNES_8_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 1 * MARTES_1_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 2 * MARTES_2_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 3 * MARTES_3_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 4 * MARTES_4_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 5 * MARTES_5_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 6 * MARTES_6_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 7 * MARTES_7_2 )
prob += (MAXIMA_FRANJA_MARTES_2 >= 8 * MARTES_8_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 1 * MIERCOLES_1_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 2 * MIERCOLES_2_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 3 * MIERCOLES_3_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 4 * MIERCOLES_4_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 5 * MIERCOLES_5_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 6 * MIERCOLES_6_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 7 * MIERCOLES_7_2 )
prob += (MAXIMA_FRANJA_MIERCOLES_2 >= 8 * MIERCOLES_8_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 1 * JUEVES_1_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 2 * JUEVES_2_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 3 * JUEVES_3_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 4 * JUEVES_4_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 5 * JUEVES_5_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 6 * JUEVES_6_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 7 * JUEVES_7_2 )
prob += (MAXIMA_FRANJA_JUEVES_2 >= 8 * JUEVES_8_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 1 * VIERNES_1_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 2 * VIERNES_2_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 3 * VIERNES_3_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 4 * VIERNES_4_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 5 * VIERNES_5_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 6 * VIERNES_6_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 7 * VIERNES_7_2 )
prob += (MAXIMA_FRANJA_VIERNES_2 >= 8 * VIERNES_8_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 1 * SABADO_1_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 2 * SABADO_2_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 3 * SABADO_3_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 4 * SABADO_4_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 5 * SABADO_5_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 6 * SABADO_6_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 7 * SABADO_7_2 )
prob += (MAXIMA_FRANJA_SABADO_2 >= 8 * SABADO_8_2 )

#Numero de franja horaria menor por dia por cuatrimestre

prob += (MINIMA_FRANJA_LUNES_1 <= 1 * LUNES_1_1 + (1 - LUNES_1_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 2 * LUNES_2_1 + (1 - LUNES_2_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 3 * LUNES_3_1 + (1 - LUNES_3_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 4 * LUNES_4_1 + (1 - LUNES_4_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 5 * LUNES_5_1 + (1 - LUNES_5_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 6 * LUNES_6_1 + (1 - LUNES_6_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 7 * LUNES_7_1 + (1 - LUNES_7_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= 8 * LUNES_8_1 + (1 - LUNES_8_1) * 10000 )
prob += (MINIMA_FRANJA_LUNES_1 <= OCUPADO_LUNES_1 * 10000)
prob += (MINIMA_FRANJA_MARTES_1 <= 1 * MARTES_1_1 + (1 - MARTES_1_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 2 * MARTES_2_1 + (1 - MARTES_2_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 3 * MARTES_3_1 + (1 - MARTES_3_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 4 * MARTES_4_1 + (1 - MARTES_4_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 5 * MARTES_5_1 + (1 - MARTES_5_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 6 * MARTES_6_1 + (1 - MARTES_6_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 7 * MARTES_7_1 + (1 - MARTES_7_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= 8 * MARTES_8_1 + (1 - MARTES_8_1) * 10000 )
prob += (MINIMA_FRANJA_MARTES_1 <= OCUPADO_MARTES_1 * 10000)
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 1 * MIERCOLES_1_1 + (1 - MIERCOLES_1_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 2 * MIERCOLES_2_1 + (1 - MIERCOLES_2_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 3 * MIERCOLES_3_1 + (1 - MIERCOLES_3_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 4 * MIERCOLES_4_1 + (1 - MIERCOLES_4_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 5 * MIERCOLES_5_1 + (1 - MIERCOLES_5_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 6 * MIERCOLES_6_1 + (1 - MIERCOLES_6_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 7 * MIERCOLES_7_1 + (1 - MIERCOLES_7_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= 8 * MIERCOLES_8_1 + (1 - MIERCOLES_8_1) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_1 <= OCUPADO_MIERCOLES_1 * 10000)
prob += (MINIMA_FRANJA_JUEVES_1 <= 1 * JUEVES_1_1 + (1 - JUEVES_1_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 2 * JUEVES_2_1 + (1 - JUEVES_2_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 3 * JUEVES_3_1 + (1 - JUEVES_3_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 4 * JUEVES_4_1 + (1 - JUEVES_4_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 5 * JUEVES_5_1 + (1 - JUEVES_5_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 6 * JUEVES_6_1 + (1 - JUEVES_6_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 7 * JUEVES_7_1 + (1 - JUEVES_7_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= 8 * JUEVES_8_1 + (1 - JUEVES_8_1) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_1 <= OCUPADO_JUEVES_1 * 10000)
prob += (MINIMA_FRANJA_VIERNES_1 <= 1 * VIERNES_1_1 + (1 - VIERNES_1_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 2 * VIERNES_2_1 + (1 - VIERNES_2_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 3 * VIERNES_3_1 + (1 - VIERNES_3_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 4 * VIERNES_4_1 + (1 - VIERNES_4_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 5 * VIERNES_5_1 + (1 - VIERNES_5_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 6 * VIERNES_6_1 + (1 - VIERNES_6_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 7 * VIERNES_7_1 + (1 - VIERNES_7_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= 8 * VIERNES_8_1 + (1 - VIERNES_8_1) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_1 <= OCUPADO_VIERNES_1 * 10000)
prob += (MINIMA_FRANJA_SABADO_1 <= 1 * SABADO_1_1 + (1 - SABADO_1_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 2 * SABADO_2_1 + (1 - SABADO_2_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 3 * SABADO_3_1 + (1 - SABADO_3_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 4 * SABADO_4_1 + (1 - SABADO_4_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 5 * SABADO_5_1 + (1 - SABADO_5_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 6 * SABADO_6_1 + (1 - SABADO_6_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 7 * SABADO_7_1 + (1 - SABADO_7_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= 8 * SABADO_8_1 + (1 - SABADO_8_1) * 10000 )
prob += (MINIMA_FRANJA_SABADO_1 <= OCUPADO_SABADO_1 * 10000)
prob += (MINIMA_FRANJA_LUNES_2 <= 1 * LUNES_1_2 + (1 - LUNES_1_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 2 * LUNES_2_2 + (1 - LUNES_2_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 3 * LUNES_3_2 + (1 - LUNES_3_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 4 * LUNES_4_2 + (1 - LUNES_4_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 5 * LUNES_5_2 + (1 - LUNES_5_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 6 * LUNES_6_2 + (1 - LUNES_6_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 7 * LUNES_7_2 + (1 - LUNES_7_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= 8 * LUNES_8_2 + (1 - LUNES_8_2) * 10000 )
prob += (MINIMA_FRANJA_LUNES_2 <= OCUPADO_LUNES_2 * 10000)
prob += (MINIMA_FRANJA_MARTES_2 <= 1 * MARTES_1_2 + (1 - MARTES_1_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 2 * MARTES_2_2 + (1 - MARTES_2_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 3 * MARTES_3_2 + (1 - MARTES_3_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 4 * MARTES_4_2 + (1 - MARTES_4_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 5 * MARTES_5_2 + (1 - MARTES_5_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 6 * MARTES_6_2 + (1 - MARTES_6_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 7 * MARTES_7_2 + (1 - MARTES_7_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= 8 * MARTES_8_2 + (1 - MARTES_8_2) * 10000 )
prob += (MINIMA_FRANJA_MARTES_2 <= OCUPADO_MARTES_2 * 10000)
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 1 * MIERCOLES_1_2 + (1 - MIERCOLES_1_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 2 * MIERCOLES_2_2 + (1 - MIERCOLES_2_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 3 * MIERCOLES_3_2 + (1 - MIERCOLES_3_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 4 * MIERCOLES_4_2 + (1 - MIERCOLES_4_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 5 * MIERCOLES_5_2 + (1 - MIERCOLES_5_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 6 * MIERCOLES_6_2 + (1 - MIERCOLES_6_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 7 * MIERCOLES_7_2 + (1 - MIERCOLES_7_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= 8 * MIERCOLES_8_2 + (1 - MIERCOLES_8_2) * 10000 )
prob += (MINIMA_FRANJA_MIERCOLES_2 <= OCUPADO_MIERCOLES_2 * 10000)
prob += (MINIMA_FRANJA_JUEVES_2 <= 1 * JUEVES_1_2 + (1 - JUEVES_1_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 2 * JUEVES_2_2 + (1 - JUEVES_2_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 3 * JUEVES_3_2 + (1 - JUEVES_3_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 4 * JUEVES_4_2 + (1 - JUEVES_4_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 5 * JUEVES_5_2 + (1 - JUEVES_5_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 6 * JUEVES_6_2 + (1 - JUEVES_6_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 7 * JUEVES_7_2 + (1 - JUEVES_7_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= 8 * JUEVES_8_2 + (1 - JUEVES_8_2) * 10000 )
prob += (MINIMA_FRANJA_JUEVES_2 <= OCUPADO_JUEVES_2 * 10000)
prob += (MINIMA_FRANJA_VIERNES_2 <= 1 * VIERNES_1_2 + (1 - VIERNES_1_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 2 * VIERNES_2_2 + (1 - VIERNES_2_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 3 * VIERNES_3_2 + (1 - VIERNES_3_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 4 * VIERNES_4_2 + (1 - VIERNES_4_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 5 * VIERNES_5_2 + (1 - VIERNES_5_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 6 * VIERNES_6_2 + (1 - VIERNES_6_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 7 * VIERNES_7_2 + (1 - VIERNES_7_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= 8 * VIERNES_8_2 + (1 - VIERNES_8_2) * 10000 )
prob += (MINIMA_FRANJA_VIERNES_2 <= OCUPADO_VIERNES_2 * 10000)
prob += (MINIMA_FRANJA_SABADO_2 <= 1 * SABADO_1_2 + (1 - SABADO_1_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 2 * SABADO_2_2 + (1 - SABADO_2_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 3 * SABADO_3_2 + (1 - SABADO_3_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 4 * SABADO_4_2 + (1 - SABADO_4_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 5 * SABADO_5_2 + (1 - SABADO_5_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 6 * SABADO_6_2 + (1 - SABADO_6_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 7 * SABADO_7_2 + (1 - SABADO_7_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= 8 * SABADO_8_2 + (1 - SABADO_8_2) * 10000 )
prob += (MINIMA_FRANJA_SABADO_2 <= OCUPADO_SABADO_2 * 10000)

#Si alguna de las franjas horarias del dia esta ocupada, entonces el dia esta ocupado

prob += (OCUPADO_LUNES_1 >= LUNES_1_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_2_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_3_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_4_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_5_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_6_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_7_1 )
prob += (OCUPADO_LUNES_1 >= LUNES_8_1 )
prob += (OCUPADO_LUNES_1 <= LUNES_1_1 + LUNES_2_1 + LUNES_3_1 + LUNES_4_1 + LUNES_5_1 + LUNES_6_1 + LUNES_7_1 + LUNES_8_1)

prob += (OCUPADO_MARTES_1 >= MARTES_1_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_2_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_3_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_4_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_5_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_6_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_7_1 )
prob += (OCUPADO_MARTES_1 >= MARTES_8_1 )
prob += (OCUPADO_MARTES_1 <= MARTES_1_1 + MARTES_2_1 + MARTES_3_1 + MARTES_4_1 + MARTES_5_1 + MARTES_6_1 + MARTES_7_1 + MARTES_8_1)

prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_1_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_2_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_3_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_4_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_5_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_6_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_7_1 )
prob += (OCUPADO_MIERCOLES_1 >= MIERCOLES_8_1 )
prob += (OCUPADO_MIERCOLES_1 <= MIERCOLES_1_1 + MIERCOLES_2_1 + MIERCOLES_3_1 + MIERCOLES_4_1 + MIERCOLES_5_1 + MIERCOLES_6_1 + MIERCOLES_7_1 + MIERCOLES_8_1)

prob += (OCUPADO_JUEVES_1 >= JUEVES_1_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_2_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_3_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_4_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_5_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_6_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_7_1 )
prob += (OCUPADO_JUEVES_1 >= JUEVES_8_1 )
prob += (OCUPADO_JUEVES_1 <= JUEVES_1_1 + JUEVES_2_1 + JUEVES_3_1 + JUEVES_4_1 + JUEVES_5_1 + JUEVES_6_1 + JUEVES_7_1 + JUEVES_8_1)

prob += (OCUPADO_VIERNES_1 >= VIERNES_1_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_2_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_3_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_4_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_5_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_6_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_7_1 )
prob += (OCUPADO_VIERNES_1 >= VIERNES_8_1 )
prob += (OCUPADO_VIERNES_1 <= VIERNES_1_1 + VIERNES_2_1 + VIERNES_3_1 + VIERNES_4_1 + VIERNES_5_1 + VIERNES_6_1 + VIERNES_7_1 + VIERNES_8_1)

prob += (OCUPADO_SABADO_1 >= SABADO_1_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_2_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_3_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_4_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_5_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_6_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_7_1 )
prob += (OCUPADO_SABADO_1 >= SABADO_8_1 )
prob += (OCUPADO_SABADO_1 <= SABADO_1_1 + SABADO_2_1 + SABADO_3_1 + SABADO_4_1 + SABADO_5_1 + SABADO_6_1 + SABADO_7_1 + SABADO_8_1)

prob += (OCUPADO_LUNES_2 >= LUNES_1_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_2_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_3_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_4_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_5_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_6_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_7_2 )
prob += (OCUPADO_LUNES_2 >= LUNES_8_2 )
prob += (OCUPADO_LUNES_2 <= LUNES_1_2 + LUNES_2_2 + LUNES_3_2 + LUNES_4_2 + LUNES_5_2 + LUNES_6_2 + LUNES_7_2 + LUNES_8_2)

prob += (OCUPADO_MARTES_2 >= MARTES_1_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_2_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_3_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_4_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_5_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_6_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_7_2 )
prob += (OCUPADO_MARTES_2 >= MARTES_8_2 )
prob += (OCUPADO_MARTES_2 <= MARTES_1_2 + MARTES_2_2 + MARTES_3_2 + MARTES_4_2 + MARTES_5_2 + MARTES_6_2 + MARTES_7_2 + MARTES_8_2)

prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_1_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_2_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_3_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_4_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_5_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_6_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_7_2 )
prob += (OCUPADO_MIERCOLES_2 >= MIERCOLES_8_2 )
prob += (OCUPADO_MIERCOLES_2 <= MIERCOLES_1_2 + MIERCOLES_2_2 + MIERCOLES_3_2 + MIERCOLES_4_2 + MIERCOLES_5_2 + MIERCOLES_6_2 + MIERCOLES_7_2 + MIERCOLES_8_2)

prob += (OCUPADO_JUEVES_2 >= JUEVES_1_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_2_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_3_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_4_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_5_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_6_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_7_2 )
prob += (OCUPADO_JUEVES_2 >= JUEVES_8_2 )
prob += (OCUPADO_JUEVES_2 <= JUEVES_1_2 + JUEVES_2_2 + JUEVES_3_2 + JUEVES_4_2 + JUEVES_5_2 + JUEVES_6_2 + JUEVES_7_2 + JUEVES_8_2)

prob += (OCUPADO_VIERNES_2 >= VIERNES_1_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_2_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_3_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_4_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_5_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_6_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_7_2 )
prob += (OCUPADO_VIERNES_2 >= VIERNES_8_2 )
prob += (OCUPADO_VIERNES_2 <= VIERNES_1_2 + VIERNES_2_2 + VIERNES_3_2 + VIERNES_4_2 + VIERNES_5_2 + VIERNES_6_2 + VIERNES_7_2 + VIERNES_8_2)

prob += (OCUPADO_SABADO_2 >= SABADO_1_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_2_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_3_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_4_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_5_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_6_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_7_2 )
prob += (OCUPADO_SABADO_2 >= SABADO_8_2 )
prob += (OCUPADO_SABADO_2 <= SABADO_1_2 + SABADO_2_2 + SABADO_3_2 + SABADO_4_2 + SABADO_5_2 + SABADO_6_2 + SABADO_7_2 + SABADO_8_2)

#Calcular la cantidad de franjas libres entre la primer y la ultima franja ocupada en el dia.
#Si en el dia no se cursan materias, da 0.

prob += (MAXIMA_FRANJA_LUNES_1 + OCUPADO_LUNES_1 - MINIMA_FRANJA_LUNES_1 - (LUNES_1_1 + LUNES_2_1 + LUNES_3_1 + LUNES_4_1 + LUNES_5_1 + LUNES_6_1 + LUNES_7_1 + LUNES_8_1) <= HORAS_LIBRES_LUNES_1)
prob += (MAXIMA_FRANJA_LUNES_1 + OCUPADO_LUNES_1 - MINIMA_FRANJA_LUNES_1 - (LUNES_1_1 + LUNES_2_1 + LUNES_3_1 + LUNES_4_1 + LUNES_5_1 + LUNES_6_1 + LUNES_7_1 + LUNES_8_1) >= HORAS_LIBRES_LUNES_1)
prob += (MAXIMA_FRANJA_MARTES_1 + OCUPADO_MARTES_1 - MINIMA_FRANJA_MARTES_1 - (MARTES_1_1 + MARTES_2_1 + MARTES_3_1 + MARTES_4_1 + MARTES_5_1 + MARTES_6_1 + MARTES_7_1 + MARTES_8_1) <= HORAS_LIBRES_MARTES_1)
prob += (MAXIMA_FRANJA_MARTES_1 + OCUPADO_MARTES_1 - MINIMA_FRANJA_MARTES_1 - (MARTES_1_1 + MARTES_2_1 + MARTES_3_1 + MARTES_4_1 + MARTES_5_1 + MARTES_6_1 + MARTES_7_1 + MARTES_8_1) >= HORAS_LIBRES_MARTES_1)
prob += (MAXIMA_FRANJA_MIERCOLES_1 + OCUPADO_MIERCOLES_1 - MINIMA_FRANJA_MIERCOLES_1 - (MIERCOLES_1_1 + MIERCOLES_2_1 + MIERCOLES_3_1 + MIERCOLES_4_1 + MIERCOLES_5_1 + MIERCOLES_6_1 + MIERCOLES_7_1 + MIERCOLES_8_1) <= HORAS_LIBRES_MIERCOLES_1)
prob += (MAXIMA_FRANJA_MIERCOLES_1 + OCUPADO_MIERCOLES_1 - MINIMA_FRANJA_MIERCOLES_1 - (MIERCOLES_1_1 + MIERCOLES_2_1 + MIERCOLES_3_1 + MIERCOLES_4_1 + MIERCOLES_5_1 + MIERCOLES_6_1 + MIERCOLES_7_1 + MIERCOLES_8_1) >= HORAS_LIBRES_MIERCOLES_1)
prob += (MAXIMA_FRANJA_JUEVES_1 + OCUPADO_JUEVES_1 - MINIMA_FRANJA_JUEVES_1 - (JUEVES_1_1 + JUEVES_2_1 + JUEVES_3_1 + JUEVES_4_1 + JUEVES_5_1 + JUEVES_6_1 + JUEVES_7_1 + JUEVES_8_1) <= HORAS_LIBRES_JUEVES_1)
prob += (MAXIMA_FRANJA_JUEVES_1 + OCUPADO_JUEVES_1 - MINIMA_FRANJA_JUEVES_1 - (JUEVES_1_1 + JUEVES_2_1 + JUEVES_3_1 + JUEVES_4_1 + JUEVES_5_1 + JUEVES_6_1 + JUEVES_7_1 + JUEVES_8_1) >= HORAS_LIBRES_JUEVES_1)
prob += (MAXIMA_FRANJA_VIERNES_1 + OCUPADO_VIERNES_1 - MINIMA_FRANJA_VIERNES_1 - (VIERNES_1_1 + VIERNES_2_1 + VIERNES_3_1 + VIERNES_4_1 + VIERNES_5_1 + VIERNES_6_1 + VIERNES_7_1 + VIERNES_8_1) <= HORAS_LIBRES_VIERNES_1)
prob += (MAXIMA_FRANJA_VIERNES_1 + OCUPADO_VIERNES_1 - MINIMA_FRANJA_VIERNES_1 - (VIERNES_1_1 + VIERNES_2_1 + VIERNES_3_1 + VIERNES_4_1 + VIERNES_5_1 + VIERNES_6_1 + VIERNES_7_1 + VIERNES_8_1) >= HORAS_LIBRES_VIERNES_1)
prob += (MAXIMA_FRANJA_SABADO_1 + OCUPADO_SABADO_1 - MINIMA_FRANJA_SABADO_1 - (SABADO_1_1 + SABADO_2_1 + SABADO_3_1 + SABADO_4_1 + SABADO_5_1 + SABADO_6_1 + SABADO_7_1 + SABADO_8_1) <= HORAS_LIBRES_SABADO_1)
prob += (MAXIMA_FRANJA_SABADO_1 + OCUPADO_SABADO_1 - MINIMA_FRANJA_SABADO_1 - (SABADO_1_1 + SABADO_2_1 + SABADO_3_1 + SABADO_4_1 + SABADO_5_1 + SABADO_6_1 + SABADO_7_1 + SABADO_8_1) >= HORAS_LIBRES_SABADO_1)
prob += (MAXIMA_FRANJA_LUNES_2 + OCUPADO_LUNES_2 - MINIMA_FRANJA_LUNES_2 - (LUNES_1_2 + LUNES_2_2 + LUNES_3_2 + LUNES_4_2 + LUNES_5_2 + LUNES_6_2 + LUNES_7_2 + LUNES_8_2) <= HORAS_LIBRES_LUNES_2)
prob += (MAXIMA_FRANJA_LUNES_2 + OCUPADO_LUNES_2 - MINIMA_FRANJA_LUNES_2 - (LUNES_1_2 + LUNES_2_2 + LUNES_3_2 + LUNES_4_2 + LUNES_5_2 + LUNES_6_2 + LUNES_7_2 + LUNES_8_2) >= HORAS_LIBRES_LUNES_2)
prob += (MAXIMA_FRANJA_MARTES_2 + OCUPADO_MARTES_2 - MINIMA_FRANJA_MARTES_2 - (MARTES_1_2 + MARTES_2_2 + MARTES_3_2 + MARTES_4_2 + MARTES_5_2 + MARTES_6_2 + MARTES_7_2 + MARTES_8_2) <= HORAS_LIBRES_MARTES_2)
prob += (MAXIMA_FRANJA_MARTES_2 + OCUPADO_MARTES_2 - MINIMA_FRANJA_MARTES_2 - (MARTES_1_2 + MARTES_2_2 + MARTES_3_2 + MARTES_4_2 + MARTES_5_2 + MARTES_6_2 + MARTES_7_2 + MARTES_8_2) >= HORAS_LIBRES_MARTES_2)
prob += (MAXIMA_FRANJA_MIERCOLES_2 + OCUPADO_MIERCOLES_2 - MINIMA_FRANJA_MIERCOLES_2 - (MIERCOLES_1_2 + MIERCOLES_2_2 + MIERCOLES_3_2 + MIERCOLES_4_2 + MIERCOLES_5_2 + MIERCOLES_6_2 + MIERCOLES_7_2 + MIERCOLES_8_2) <= HORAS_LIBRES_MIERCOLES_2)
prob += (MAXIMA_FRANJA_MIERCOLES_2 + OCUPADO_MIERCOLES_2 - MINIMA_FRANJA_MIERCOLES_2 - (MIERCOLES_1_2 + MIERCOLES_2_2 + MIERCOLES_3_2 + MIERCOLES_4_2 + MIERCOLES_5_2 + MIERCOLES_6_2 + MIERCOLES_7_2 + MIERCOLES_8_2) >= HORAS_LIBRES_MIERCOLES_2)
prob += (MAXIMA_FRANJA_JUEVES_2 + OCUPADO_JUEVES_2 - MINIMA_FRANJA_JUEVES_2 - (JUEVES_1_2 + JUEVES_2_2 + JUEVES_3_2 + JUEVES_4_2 + JUEVES_5_2 + JUEVES_6_2 + JUEVES_7_2 + JUEVES_8_2) <= HORAS_LIBRES_JUEVES_2)
prob += (MAXIMA_FRANJA_JUEVES_2 + OCUPADO_JUEVES_2 - MINIMA_FRANJA_JUEVES_2 - (JUEVES_1_2 + JUEVES_2_2 + JUEVES_3_2 + JUEVES_4_2 + JUEVES_5_2 + JUEVES_6_2 + JUEVES_7_2 + JUEVES_8_2) >= HORAS_LIBRES_JUEVES_2)
prob += (MAXIMA_FRANJA_VIERNES_2 + OCUPADO_VIERNES_2 - MINIMA_FRANJA_VIERNES_2 - (VIERNES_1_2 + VIERNES_2_2 + VIERNES_3_2 + VIERNES_4_2 + VIERNES_5_2 + VIERNES_6_2 + VIERNES_7_2 + VIERNES_8_2) <= HORAS_LIBRES_VIERNES_2)
prob += (MAXIMA_FRANJA_VIERNES_2 + OCUPADO_VIERNES_2 - MINIMA_FRANJA_VIERNES_2 - (VIERNES_1_2 + VIERNES_2_2 + VIERNES_3_2 + VIERNES_4_2 + VIERNES_5_2 + VIERNES_6_2 + VIERNES_7_2 + VIERNES_8_2) >= HORAS_LIBRES_VIERNES_2)
prob += (MAXIMA_FRANJA_SABADO_2 + OCUPADO_SABADO_2 - MINIMA_FRANJA_SABADO_2 - (SABADO_1_2 + SABADO_2_2 + SABADO_3_2 + SABADO_4_2 + SABADO_5_2 + SABADO_6_2 + SABADO_7_2 + SABADO_8_2) <= HORAS_LIBRES_SABADO_2)
prob += (MAXIMA_FRANJA_SABADO_2 + OCUPADO_SABADO_2 - MINIMA_FRANJA_SABADO_2 - (SABADO_1_2 + SABADO_2_2 + SABADO_3_2 + SABADO_4_2 + SABADO_5_2 + SABADO_6_2 + SABADO_7_2 + SABADO_8_2) >= HORAS_LIBRES_SABADO_2)

#Total de horas libres entre materias en el plan, es la suma de las horas libres de cada dia por cuatrimestre

prob += (HORAS_LIBRES_LUNES_1 + HORAS_LIBRES_MARTES_1 + HORAS_LIBRES_MIERCOLES_1 + HORAS_LIBRES_JUEVES_1 + HORAS_LIBRES_VIERNES_1 + HORAS_LIBRES_SABADO_1 + HORAS_LIBRES_LUNES_2 + HORAS_LIBRES_MARTES_2 + HORAS_LIBRES_MIERCOLES_2 + HORAS_LIBRES_JUEVES_2 + HORAS_LIBRES_VIERNES_2 + HORAS_LIBRES_SABADO_2 <= HORAS_LIBRES_TOTALES)
prob += (HORAS_LIBRES_LUNES_1 + HORAS_LIBRES_MARTES_1 + HORAS_LIBRES_MIERCOLES_1 + HORAS_LIBRES_JUEVES_1 + HORAS_LIBRES_VIERNES_1 + HORAS_LIBRES_SABADO_1 + HORAS_LIBRES_LUNES_2 + HORAS_LIBRES_MARTES_2 + HORAS_LIBRES_MIERCOLES_2 + HORAS_LIBRES_JUEVES_2 + HORAS_LIBRES_VIERNES_2 + HORAS_LIBRES_SABADO_2 >= HORAS_LIBRES_TOTALES)

# Definicion de la funcion objetivo a minimizar.

prob += 1*TOTAL_CUATRIMESTRES + 1*HORAS_LIBRES_TOTALES

# Resolucion del problema

tiempo_inicial = time()
status = prob.solve(GLPK(msg=0))
tiempo_final = time()
DURACION_EJECUCION_PULP = tiempo_final - tiempo_inicial
print('Duracion: {}'.format(DURACION_EJECUCION_PULP))
with open('resultados_tests/test_correlatividades_se_hacen_en_orden_resultados_pulp.py', 'w') as arch:
    arch.write("tiempo;{}".format(DURACION_EJECUCION_PULP) + "\n")
    arch.write("Y_H_1;{}".format(value(Y_H_1)) + "\n")
    arch.write("Y_H_2;{}".format(value(Y_H_2)) + "\n")
    arch.write("Y_D_1;{}".format(value(Y_D_1)) + "\n")
    arch.write("Y_D_2;{}".format(value(Y_D_2)) + "\n")
    arch.write("Y_I_1;{}".format(value(Y_I_1)) + "\n")
    arch.write("Y_I_2;{}".format(value(Y_I_2)) + "\n")
    arch.write("Y_C_1;{}".format(value(Y_C_1)) + "\n")
    arch.write("Y_C_2;{}".format(value(Y_C_2)) + "\n")
    arch.write("Y_E_1;{}".format(value(Y_E_1)) + "\n")
    arch.write("Y_E_2;{}".format(value(Y_E_2)) + "\n")
    arch.write("Y_J_1;{}".format(value(Y_J_1)) + "\n")
    arch.write("Y_J_2;{}".format(value(Y_J_2)) + "\n")
    arch.write("Y_A_1;{}".format(value(Y_A_1)) + "\n")
    arch.write("Y_A_2;{}".format(value(Y_A_2)) + "\n")
    arch.write("Y_G_1;{}".format(value(Y_G_1)) + "\n")
    arch.write("Y_G_2;{}".format(value(Y_G_2)) + "\n")
    arch.write("Y_B_1;{}".format(value(Y_B_1)) + "\n")
    arch.write("Y_B_2;{}".format(value(Y_B_2)) + "\n")
    arch.write("Y_F_1;{}".format(value(Y_F_1)) + "\n")
    arch.write("Y_F_2;{}".format(value(Y_F_2)) + "\n")
    arch.write("CH;{}".format(value(CH)) + "\n")
    arch.write("CD;{}".format(value(CD)) + "\n")
    arch.write("CI;{}".format(value(CI)) + "\n")
    arch.write("CC;{}".format(value(CC)) + "\n")
    arch.write("CE;{}".format(value(CE)) + "\n")
    arch.write("CJ;{}".format(value(CJ)) + "\n")
    arch.write("CA;{}".format(value(CA)) + "\n")
    arch.write("CG;{}".format(value(CG)) + "\n")
    arch.write("CB;{}".format(value(CB)) + "\n")
    arch.write("CF;{}".format(value(CF)) + "\n")
    arch.write("TOTAL_CUATRIMESTRES;{}".format(value(TOTAL_CUATRIMESTRES)) + "\n")
    arch.write("CRED0;{}".format(value(CRED0)) + "\n")
    arch.write("CRED1;{}".format(value(CRED1)) + "\n")
    arch.write("H_H_Curso1H_1;{}".format(value(H_H_Curso1H_1)) + "\n")
    arch.write("H_D_Curso1D_1;{}".format(value(H_D_Curso1D_1)) + "\n")
    arch.write("H_I_Curso1I_1;{}".format(value(H_I_Curso1I_1)) + "\n")
    arch.write("H_C_Curso1C_1;{}".format(value(H_C_Curso1C_1)) + "\n")
    arch.write("H_E_Curso1E_1;{}".format(value(H_E_Curso1E_1)) + "\n")
    arch.write("H_J_Curso1J_1;{}".format(value(H_J_Curso1J_1)) + "\n")
    arch.write("H_A_Curso1A_1;{}".format(value(H_A_Curso1A_1)) + "\n")
    arch.write("H_G_Curso1G_1;{}".format(value(H_G_Curso1G_1)) + "\n")
    arch.write("H_B_Curso1B_1;{}".format(value(H_B_Curso1B_1)) + "\n")
    arch.write("H_F_Curso1F_1;{}".format(value(H_F_Curso1F_1)) + "\n")
    arch.write("H_H_Curso1H_2;{}".format(value(H_H_Curso1H_2)) + "\n")
    arch.write("H_D_Curso1D_2;{}".format(value(H_D_Curso1D_2)) + "\n")
    arch.write("H_I_Curso1I_2;{}".format(value(H_I_Curso1I_2)) + "\n")
    arch.write("H_C_Curso1C_2;{}".format(value(H_C_Curso1C_2)) + "\n")
    arch.write("H_E_Curso1E_2;{}".format(value(H_E_Curso1E_2)) + "\n")
    arch.write("H_J_Curso1J_2;{}".format(value(H_J_Curso1J_2)) + "\n")
    arch.write("H_A_Curso1A_2;{}".format(value(H_A_Curso1A_2)) + "\n")
    arch.write("H_G_Curso1G_2;{}".format(value(H_G_Curso1G_2)) + "\n")
    arch.write("H_B_Curso1B_2;{}".format(value(H_B_Curso1B_2)) + "\n")
    arch.write("H_F_Curso1F_2;{}".format(value(H_F_Curso1F_2)) + "\n")
    arch.write("LUNES_1_1;{}".format(value(LUNES_1_1)) + "\n")
    arch.write("LUNES_2_1;{}".format(value(LUNES_2_1)) + "\n")
    arch.write("LUNES_3_1;{}".format(value(LUNES_3_1)) + "\n")
    arch.write("LUNES_4_1;{}".format(value(LUNES_4_1)) + "\n")
    arch.write("LUNES_5_1;{}".format(value(LUNES_5_1)) + "\n")
    arch.write("LUNES_6_1;{}".format(value(LUNES_6_1)) + "\n")
    arch.write("LUNES_7_1;{}".format(value(LUNES_7_1)) + "\n")
    arch.write("LUNES_8_1;{}".format(value(LUNES_8_1)) + "\n")
    arch.write("MARTES_1_1;{}".format(value(MARTES_1_1)) + "\n")
    arch.write("MARTES_2_1;{}".format(value(MARTES_2_1)) + "\n")
    arch.write("MARTES_3_1;{}".format(value(MARTES_3_1)) + "\n")
    arch.write("MARTES_4_1;{}".format(value(MARTES_4_1)) + "\n")
    arch.write("MARTES_5_1;{}".format(value(MARTES_5_1)) + "\n")
    arch.write("MARTES_6_1;{}".format(value(MARTES_6_1)) + "\n")
    arch.write("MARTES_7_1;{}".format(value(MARTES_7_1)) + "\n")
    arch.write("MARTES_8_1;{}".format(value(MARTES_8_1)) + "\n")
    arch.write("MIERCOLES_1_1;{}".format(value(MIERCOLES_1_1)) + "\n")
    arch.write("MIERCOLES_2_1;{}".format(value(MIERCOLES_2_1)) + "\n")
    arch.write("MIERCOLES_3_1;{}".format(value(MIERCOLES_3_1)) + "\n")
    arch.write("MIERCOLES_4_1;{}".format(value(MIERCOLES_4_1)) + "\n")
    arch.write("MIERCOLES_5_1;{}".format(value(MIERCOLES_5_1)) + "\n")
    arch.write("MIERCOLES_6_1;{}".format(value(MIERCOLES_6_1)) + "\n")
    arch.write("MIERCOLES_7_1;{}".format(value(MIERCOLES_7_1)) + "\n")
    arch.write("MIERCOLES_8_1;{}".format(value(MIERCOLES_8_1)) + "\n")
    arch.write("JUEVES_1_1;{}".format(value(JUEVES_1_1)) + "\n")
    arch.write("JUEVES_2_1;{}".format(value(JUEVES_2_1)) + "\n")
    arch.write("JUEVES_3_1;{}".format(value(JUEVES_3_1)) + "\n")
    arch.write("JUEVES_4_1;{}".format(value(JUEVES_4_1)) + "\n")
    arch.write("JUEVES_5_1;{}".format(value(JUEVES_5_1)) + "\n")
    arch.write("JUEVES_6_1;{}".format(value(JUEVES_6_1)) + "\n")
    arch.write("JUEVES_7_1;{}".format(value(JUEVES_7_1)) + "\n")
    arch.write("JUEVES_8_1;{}".format(value(JUEVES_8_1)) + "\n")
    arch.write("VIERNES_1_1;{}".format(value(VIERNES_1_1)) + "\n")
    arch.write("VIERNES_2_1;{}".format(value(VIERNES_2_1)) + "\n")
    arch.write("VIERNES_3_1;{}".format(value(VIERNES_3_1)) + "\n")
    arch.write("VIERNES_4_1;{}".format(value(VIERNES_4_1)) + "\n")
    arch.write("VIERNES_5_1;{}".format(value(VIERNES_5_1)) + "\n")
    arch.write("VIERNES_6_1;{}".format(value(VIERNES_6_1)) + "\n")
    arch.write("VIERNES_7_1;{}".format(value(VIERNES_7_1)) + "\n")
    arch.write("VIERNES_8_1;{}".format(value(VIERNES_8_1)) + "\n")
    arch.write("SABADO_1_1;{}".format(value(SABADO_1_1)) + "\n")
    arch.write("SABADO_2_1;{}".format(value(SABADO_2_1)) + "\n")
    arch.write("SABADO_3_1;{}".format(value(SABADO_3_1)) + "\n")
    arch.write("SABADO_4_1;{}".format(value(SABADO_4_1)) + "\n")
    arch.write("SABADO_5_1;{}".format(value(SABADO_5_1)) + "\n")
    arch.write("SABADO_6_1;{}".format(value(SABADO_6_1)) + "\n")
    arch.write("SABADO_7_1;{}".format(value(SABADO_7_1)) + "\n")
    arch.write("SABADO_8_1;{}".format(value(SABADO_8_1)) + "\n")
    arch.write("LUNES_1_2;{}".format(value(LUNES_1_2)) + "\n")
    arch.write("LUNES_2_2;{}".format(value(LUNES_2_2)) + "\n")
    arch.write("LUNES_3_2;{}".format(value(LUNES_3_2)) + "\n")
    arch.write("LUNES_4_2;{}".format(value(LUNES_4_2)) + "\n")
    arch.write("LUNES_5_2;{}".format(value(LUNES_5_2)) + "\n")
    arch.write("LUNES_6_2;{}".format(value(LUNES_6_2)) + "\n")
    arch.write("LUNES_7_2;{}".format(value(LUNES_7_2)) + "\n")
    arch.write("LUNES_8_2;{}".format(value(LUNES_8_2)) + "\n")
    arch.write("MARTES_1_2;{}".format(value(MARTES_1_2)) + "\n")
    arch.write("MARTES_2_2;{}".format(value(MARTES_2_2)) + "\n")
    arch.write("MARTES_3_2;{}".format(value(MARTES_3_2)) + "\n")
    arch.write("MARTES_4_2;{}".format(value(MARTES_4_2)) + "\n")
    arch.write("MARTES_5_2;{}".format(value(MARTES_5_2)) + "\n")
    arch.write("MARTES_6_2;{}".format(value(MARTES_6_2)) + "\n")
    arch.write("MARTES_7_2;{}".format(value(MARTES_7_2)) + "\n")
    arch.write("MARTES_8_2;{}".format(value(MARTES_8_2)) + "\n")
    arch.write("MIERCOLES_1_2;{}".format(value(MIERCOLES_1_2)) + "\n")
    arch.write("MIERCOLES_2_2;{}".format(value(MIERCOLES_2_2)) + "\n")
    arch.write("MIERCOLES_3_2;{}".format(value(MIERCOLES_3_2)) + "\n")
    arch.write("MIERCOLES_4_2;{}".format(value(MIERCOLES_4_2)) + "\n")
    arch.write("MIERCOLES_5_2;{}".format(value(MIERCOLES_5_2)) + "\n")
    arch.write("MIERCOLES_6_2;{}".format(value(MIERCOLES_6_2)) + "\n")
    arch.write("MIERCOLES_7_2;{}".format(value(MIERCOLES_7_2)) + "\n")
    arch.write("MIERCOLES_8_2;{}".format(value(MIERCOLES_8_2)) + "\n")
    arch.write("JUEVES_1_2;{}".format(value(JUEVES_1_2)) + "\n")
    arch.write("JUEVES_2_2;{}".format(value(JUEVES_2_2)) + "\n")
    arch.write("JUEVES_3_2;{}".format(value(JUEVES_3_2)) + "\n")
    arch.write("JUEVES_4_2;{}".format(value(JUEVES_4_2)) + "\n")
    arch.write("JUEVES_5_2;{}".format(value(JUEVES_5_2)) + "\n")
    arch.write("JUEVES_6_2;{}".format(value(JUEVES_6_2)) + "\n")
    arch.write("JUEVES_7_2;{}".format(value(JUEVES_7_2)) + "\n")
    arch.write("JUEVES_8_2;{}".format(value(JUEVES_8_2)) + "\n")
    arch.write("VIERNES_1_2;{}".format(value(VIERNES_1_2)) + "\n")
    arch.write("VIERNES_2_2;{}".format(value(VIERNES_2_2)) + "\n")
    arch.write("VIERNES_3_2;{}".format(value(VIERNES_3_2)) + "\n")
    arch.write("VIERNES_4_2;{}".format(value(VIERNES_4_2)) + "\n")
    arch.write("VIERNES_5_2;{}".format(value(VIERNES_5_2)) + "\n")
    arch.write("VIERNES_6_2;{}".format(value(VIERNES_6_2)) + "\n")
    arch.write("VIERNES_7_2;{}".format(value(VIERNES_7_2)) + "\n")
    arch.write("VIERNES_8_2;{}".format(value(VIERNES_8_2)) + "\n")
    arch.write("SABADO_1_2;{}".format(value(SABADO_1_2)) + "\n")
    arch.write("SABADO_2_2;{}".format(value(SABADO_2_2)) + "\n")
    arch.write("SABADO_3_2;{}".format(value(SABADO_3_2)) + "\n")
    arch.write("SABADO_4_2;{}".format(value(SABADO_4_2)) + "\n")
    arch.write("SABADO_5_2;{}".format(value(SABADO_5_2)) + "\n")
    arch.write("SABADO_6_2;{}".format(value(SABADO_6_2)) + "\n")
    arch.write("SABADO_7_2;{}".format(value(SABADO_7_2)) + "\n")
    arch.write("SABADO_8_2;{}".format(value(SABADO_8_2)) + "\n")
    arch.write("R_H_Curso1H_JUEVES_5_1;{}".format(value(R_H_Curso1H_JUEVES_5_1)) + "\n")
    arch.write("R_H_Curso1H_JUEVES_6_1;{}".format(value(R_H_Curso1H_JUEVES_6_1)) + "\n")
    arch.write("R_D_Curso1D_MARTES_5_1;{}".format(value(R_D_Curso1D_MARTES_5_1)) + "\n")
    arch.write("R_D_Curso1D_MARTES_6_1;{}".format(value(R_D_Curso1D_MARTES_6_1)) + "\n")
    arch.write("R_I_Curso1I_VIERNES_1_1;{}".format(value(R_I_Curso1I_VIERNES_1_1)) + "\n")
    arch.write("R_I_Curso1I_VIERNES_2_1;{}".format(value(R_I_Curso1I_VIERNES_2_1)) + "\n")
    arch.write("R_C_Curso1C_MARTES_1_1;{}".format(value(R_C_Curso1C_MARTES_1_1)) + "\n")
    arch.write("R_C_Curso1C_MARTES_2_1;{}".format(value(R_C_Curso1C_MARTES_2_1)) + "\n")
    arch.write("R_E_Curso1E_MIERCOLES_1_1;{}".format(value(R_E_Curso1E_MIERCOLES_1_1)) + "\n")
    arch.write("R_E_Curso1E_MIERCOLES_2_1;{}".format(value(R_E_Curso1E_MIERCOLES_2_1)) + "\n")
    arch.write("R_J_Curso1J_SABADO_1_1;{}".format(value(R_J_Curso1J_SABADO_1_1)) + "\n")
    arch.write("R_J_Curso1J_SABADO_2_1;{}".format(value(R_J_Curso1J_SABADO_2_1)) + "\n")
    arch.write("R_A_Curso1A_LUNES_1_1;{}".format(value(R_A_Curso1A_LUNES_1_1)) + "\n")
    arch.write("R_A_Curso1A_LUNES_2_1;{}".format(value(R_A_Curso1A_LUNES_2_1)) + "\n")
    arch.write("R_G_Curso1G_MIERCOLES_5_1;{}".format(value(R_G_Curso1G_MIERCOLES_5_1)) + "\n")
    arch.write("R_G_Curso1G_MIERCOLES_6_1;{}".format(value(R_G_Curso1G_MIERCOLES_6_1)) + "\n")
    arch.write("R_B_Curso1B_LUNES_5_1;{}".format(value(R_B_Curso1B_LUNES_5_1)) + "\n")
    arch.write("R_B_Curso1B_LUNES_6_1;{}".format(value(R_B_Curso1B_LUNES_6_1)) + "\n")
    arch.write("R_F_Curso1F_JUEVES_1_1;{}".format(value(R_F_Curso1F_JUEVES_1_1)) + "\n")
    arch.write("R_F_Curso1F_JUEVES_2_1;{}".format(value(R_F_Curso1F_JUEVES_2_1)) + "\n")
    arch.write("R_H_Curso1H_JUEVES_5_2;{}".format(value(R_H_Curso1H_JUEVES_5_2)) + "\n")
    arch.write("R_H_Curso1H_JUEVES_6_2;{}".format(value(R_H_Curso1H_JUEVES_6_2)) + "\n")
    arch.write("R_D_Curso1D_MARTES_5_2;{}".format(value(R_D_Curso1D_MARTES_5_2)) + "\n")
    arch.write("R_D_Curso1D_MARTES_6_2;{}".format(value(R_D_Curso1D_MARTES_6_2)) + "\n")
    arch.write("R_I_Curso1I_VIERNES_1_2;{}".format(value(R_I_Curso1I_VIERNES_1_2)) + "\n")
    arch.write("R_I_Curso1I_VIERNES_2_2;{}".format(value(R_I_Curso1I_VIERNES_2_2)) + "\n")
    arch.write("R_C_Curso1C_MARTES_1_2;{}".format(value(R_C_Curso1C_MARTES_1_2)) + "\n")
    arch.write("R_C_Curso1C_MARTES_2_2;{}".format(value(R_C_Curso1C_MARTES_2_2)) + "\n")
    arch.write("R_E_Curso1E_MIERCOLES_1_2;{}".format(value(R_E_Curso1E_MIERCOLES_1_2)) + "\n")
    arch.write("R_E_Curso1E_MIERCOLES_2_2;{}".format(value(R_E_Curso1E_MIERCOLES_2_2)) + "\n")
    arch.write("R_J_Curso1J_SABADO_1_2;{}".format(value(R_J_Curso1J_SABADO_1_2)) + "\n")
    arch.write("R_J_Curso1J_SABADO_2_2;{}".format(value(R_J_Curso1J_SABADO_2_2)) + "\n")
    arch.write("R_A_Curso1A_LUNES_1_2;{}".format(value(R_A_Curso1A_LUNES_1_2)) + "\n")
    arch.write("R_A_Curso1A_LUNES_2_2;{}".format(value(R_A_Curso1A_LUNES_2_2)) + "\n")
    arch.write("R_G_Curso1G_MIERCOLES_5_2;{}".format(value(R_G_Curso1G_MIERCOLES_5_2)) + "\n")
    arch.write("R_G_Curso1G_MIERCOLES_6_2;{}".format(value(R_G_Curso1G_MIERCOLES_6_2)) + "\n")
    arch.write("R_B_Curso1B_LUNES_5_2;{}".format(value(R_B_Curso1B_LUNES_5_2)) + "\n")
    arch.write("R_B_Curso1B_LUNES_6_2;{}".format(value(R_B_Curso1B_LUNES_6_2)) + "\n")
    arch.write("R_F_Curso1F_JUEVES_1_2;{}".format(value(R_F_Curso1F_JUEVES_1_2)) + "\n")
    arch.write("R_F_Curso1F_JUEVES_2_2;{}".format(value(R_F_Curso1F_JUEVES_2_2)) + "\n")
    arch.write("OCUPADO_LUNES_1;{}".format(value(OCUPADO_LUNES_1)) + "\n")
    arch.write("OCUPADO_MARTES_1;{}".format(value(OCUPADO_MARTES_1)) + "\n")
    arch.write("OCUPADO_MIERCOLES_1;{}".format(value(OCUPADO_MIERCOLES_1)) + "\n")
    arch.write("OCUPADO_JUEVES_1;{}".format(value(OCUPADO_JUEVES_1)) + "\n")
    arch.write("OCUPADO_VIERNES_1;{}".format(value(OCUPADO_VIERNES_1)) + "\n")
    arch.write("OCUPADO_SABADO_1;{}".format(value(OCUPADO_SABADO_1)) + "\n")
    arch.write("OCUPADO_LUNES_2;{}".format(value(OCUPADO_LUNES_2)) + "\n")
    arch.write("OCUPADO_MARTES_2;{}".format(value(OCUPADO_MARTES_2)) + "\n")
    arch.write("OCUPADO_MIERCOLES_2;{}".format(value(OCUPADO_MIERCOLES_2)) + "\n")
    arch.write("OCUPADO_JUEVES_2;{}".format(value(OCUPADO_JUEVES_2)) + "\n")
    arch.write("OCUPADO_VIERNES_2;{}".format(value(OCUPADO_VIERNES_2)) + "\n")
    arch.write("OCUPADO_SABADO_2;{}".format(value(OCUPADO_SABADO_2)) + "\n")
    arch.write("MAXIMA_FRANJA_LUNES_1;{}".format(value(MAXIMA_FRANJA_LUNES_1)) + "\n")
    arch.write("MINIMA_FRANJA_LUNES_1;{}".format(value(MINIMA_FRANJA_LUNES_1)) + "\n")
    arch.write("MAXIMA_FRANJA_MARTES_1;{}".format(value(MAXIMA_FRANJA_MARTES_1)) + "\n")
    arch.write("MINIMA_FRANJA_MARTES_1;{}".format(value(MINIMA_FRANJA_MARTES_1)) + "\n")
    arch.write("MAXIMA_FRANJA_MIERCOLES_1;{}".format(value(MAXIMA_FRANJA_MIERCOLES_1)) + "\n")
    arch.write("MINIMA_FRANJA_MIERCOLES_1;{}".format(value(MINIMA_FRANJA_MIERCOLES_1)) + "\n")
    arch.write("MAXIMA_FRANJA_JUEVES_1;{}".format(value(MAXIMA_FRANJA_JUEVES_1)) + "\n")
    arch.write("MINIMA_FRANJA_JUEVES_1;{}".format(value(MINIMA_FRANJA_JUEVES_1)) + "\n")
    arch.write("MAXIMA_FRANJA_VIERNES_1;{}".format(value(MAXIMA_FRANJA_VIERNES_1)) + "\n")
    arch.write("MINIMA_FRANJA_VIERNES_1;{}".format(value(MINIMA_FRANJA_VIERNES_1)) + "\n")
    arch.write("MAXIMA_FRANJA_SABADO_1;{}".format(value(MAXIMA_FRANJA_SABADO_1)) + "\n")
    arch.write("MINIMA_FRANJA_SABADO_1;{}".format(value(MINIMA_FRANJA_SABADO_1)) + "\n")
    arch.write("MAXIMA_FRANJA_LUNES_2;{}".format(value(MAXIMA_FRANJA_LUNES_2)) + "\n")
    arch.write("MINIMA_FRANJA_LUNES_2;{}".format(value(MINIMA_FRANJA_LUNES_2)) + "\n")
    arch.write("MAXIMA_FRANJA_MARTES_2;{}".format(value(MAXIMA_FRANJA_MARTES_2)) + "\n")
    arch.write("MINIMA_FRANJA_MARTES_2;{}".format(value(MINIMA_FRANJA_MARTES_2)) + "\n")
    arch.write("MAXIMA_FRANJA_MIERCOLES_2;{}".format(value(MAXIMA_FRANJA_MIERCOLES_2)) + "\n")
    arch.write("MINIMA_FRANJA_MIERCOLES_2;{}".format(value(MINIMA_FRANJA_MIERCOLES_2)) + "\n")
    arch.write("MAXIMA_FRANJA_JUEVES_2;{}".format(value(MAXIMA_FRANJA_JUEVES_2)) + "\n")
    arch.write("MINIMA_FRANJA_JUEVES_2;{}".format(value(MINIMA_FRANJA_JUEVES_2)) + "\n")
    arch.write("MAXIMA_FRANJA_VIERNES_2;{}".format(value(MAXIMA_FRANJA_VIERNES_2)) + "\n")
    arch.write("MINIMA_FRANJA_VIERNES_2;{}".format(value(MINIMA_FRANJA_VIERNES_2)) + "\n")
    arch.write("MAXIMA_FRANJA_SABADO_2;{}".format(value(MAXIMA_FRANJA_SABADO_2)) + "\n")
    arch.write("MINIMA_FRANJA_SABADO_2;{}".format(value(MINIMA_FRANJA_SABADO_2)) + "\n")
    arch.write("HORAS_LIBRES_LUNES_1;{}".format(value(HORAS_LIBRES_LUNES_1)) + "\n")
    arch.write("HORAS_LIBRES_MARTES_1;{}".format(value(HORAS_LIBRES_MARTES_1)) + "\n")
    arch.write("HORAS_LIBRES_MIERCOLES_1;{}".format(value(HORAS_LIBRES_MIERCOLES_1)) + "\n")
    arch.write("HORAS_LIBRES_JUEVES_1;{}".format(value(HORAS_LIBRES_JUEVES_1)) + "\n")
    arch.write("HORAS_LIBRES_VIERNES_1;{}".format(value(HORAS_LIBRES_VIERNES_1)) + "\n")
    arch.write("HORAS_LIBRES_SABADO_1;{}".format(value(HORAS_LIBRES_SABADO_1)) + "\n")
    arch.write("HORAS_LIBRES_LUNES_2;{}".format(value(HORAS_LIBRES_LUNES_2)) + "\n")
    arch.write("HORAS_LIBRES_MARTES_2;{}".format(value(HORAS_LIBRES_MARTES_2)) + "\n")
    arch.write("HORAS_LIBRES_MIERCOLES_2;{}".format(value(HORAS_LIBRES_MIERCOLES_2)) + "\n")
    arch.write("HORAS_LIBRES_JUEVES_2;{}".format(value(HORAS_LIBRES_JUEVES_2)) + "\n")
    arch.write("HORAS_LIBRES_VIERNES_2;{}".format(value(HORAS_LIBRES_VIERNES_2)) + "\n")
    arch.write("HORAS_LIBRES_SABADO_2;{}".format(value(HORAS_LIBRES_SABADO_2)) + "\n")
    arch.write("HORAS_LIBRES_TOTALES;{}".format(value(HORAS_LIBRES_TOTALES)) + "\n")
