from app.API_Rest.Services.BuscarCarrerasService import *
from app.API_Rest.Services.BuscarMateriasService import *
from app.API_Rest.Services.ObtenerMateriaService import *
from app.API_Rest.Services.ObtenerMateriasCorrelativasService import *
from app.API_Rest.Services.ObtenerCarrerasDondeSeDictaLaMateriaService import *
from app.API_Rest.Services.GuardarHorariosDesdeArchivoPDFService import *
from app.API_Rest.Services.BuscarCursosService import *
from app.API_Rest.Services.ModificarCursoService import *
from app.API_Rest.Services.ObtenerPadronAlumnoService import *
from app.API_Rest.Services.ModificarPadronAlumnoService import *
from app.API_Rest.Services.AgregarCarreraAlumnoService import *
from app.API_Rest.Services.ObtenerCarrerasAlumnoService import *
from app.API_Rest.Services.EliminarCarreraAlumnoService import *
from app.API_Rest.Services.ObtenerMateriasAlumnoService import *
from app.API_Rest.Services.AgregarMateriaAlumnoService import *
from app.API_Rest.Services.EliminarMateriaAlumnoService import *
from app.API_Rest.Services.ObtenerPreguntasEncuestaService import *
from app.API_Rest.Services.ObtenerDocentesCursoService import *
from app.API_Rest.Services.ObtenerDocentesService import *
from app.API_Rest.Services.ObtenerEncuestasAlumnoService import *
from app.API_Rest.Services.ObtenerTematicasMateriasService import *
from app.API_Rest.Services.ObtenerRespuestasEncuestaAlumnoParaPreguntasEspecificasService import *
from app.API_Rest.Services.GuardarRespuestasEncuestaAlumnoService import *
