ENTER = "\n"
NOMBRE_PROBLEMA = "Jenny_Calculo_plan_carrera"

INFINITO = 10000

LUNES = "LUNES"
MARTES = "MARTES"
MIERCOLES = "MIERCOLES"
JUEVES = "JUEVES"
VIERNES = "VIERNES"
SABADO = "SABADO"

#Tipos de materias
OBLIGATORIA = 0
ELECTIVA = 1

TIPOS_MATERIAS = {
	OBLIGATORIA: "Obligatoria",
	ELECTIVA: "Electiva"
}